### ISSUE TITLE
"Failed to install Ansible" error using bootstrap script

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/piku#124]
On a fresh install of Buster I'm getting this... 

> pi@pikuserver:~ $ curl https://piku.github.io/get | sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   215  100   215    0     0   1990      0 --:--:-- --:--:-- --:--:--  1990
> 
> Downloading piku-bootstrap here and running it.
> 
> Looks like this is your first time running piku-bootstrap.
> This script will self-install dependencies into /home/pi/.piku-bootstrap now.
> Hit enter to continue or ctrl-C to abort.
> 
>  #> Virtualenv setup not found. Installing it into /home/pi/.piku-bootstrap.
>  #> Downloading & installing Virtualenv.
>  #> Setting up the virtual environment.
>  #> Piku repo not found. Installing it into /home/pi/.piku-bootstrap/piku.
> Cloning into '/home/pi/.piku-bootstrap/piku'...
> remote: Enumerating objects: 12, done.
> remote: Counting objects: 100% (12/12), done.
> remote: Compressing objects: 100% (12/12), done.
> remote: Total 1418 (delta 3), reused 0 (delta 0), pack-reused 1406
> Receiving objects: 100% (1418/1418), 862.07 KiB | 2.36 MiB/s, done.
> Resolving deltas: 100% (822/822), done.
>  #> ansible-playbook binary not found. Installing it into /home/pi/.piku-bootstrap.
> Failed to install Ansible.
> See /home/pi/.piku-bootstrap/install.log for details (you may be missing a C compiler).

The install log shows this interesting part at the end...
>       arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-9NJ3qw/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
>       c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
>        #include <Python.h>
>                 ^~~~~~~~~~
>       compilation terminated.
>       error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
>       ----------------------------------------
>   ERROR: Command errored out with exit status 1: /home/pi/.piku-bootstrap/virtualenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ye1mun/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ye1mun/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zvEFd6/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-18etu7/overlay --compile --install-headers /home/pi/.piku-bootstrap/virtualenv/include/site/python2.7/cffi Check the logs for full command output.
>   ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/pi/.piku-bootstrap/virtualenv/bin/python /home/pi/.piku-bootstrap/virtualenv/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-18etu7/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.

**Comment by dwightmulcahy** [comment]
Had to do the following to resolve this:
`sudo apt-get install python-dev libffi-dev`

**Comment by dwightmulcahy** [comment]
ugh.  missed the "install this on your local machine"...

**Comment by chr15m** [comment]
@dwightmulcahy is there some way we can make the docs clearer? I wouldn't want this to happen to more people.

**Comment by dwightmulcahy** [comment]
@chr15m I'll PR something...  (and it's not like this is the third or fourth time that I've installed this on a rPi, just actually read the steps this time). 🤦‍♂
