### ISSUE TITLE
Not available piku-bootstrap install-cli

### ISSUE THREAD

**Issue by jsenin** [piku/piku#127]
At README.md installation refers to a way to install piku cli using `piku-bootstrap` but its only available at commit https://github.com/piku/piku/blob/60da61456ed3f44c5d6691ed7a55ecbe0dfff382/piku-bootstrap 

Readme reference:
```
To make life easier you can also install the piku helper CLI. Install it into your path e.g. ~/bin to run it from anywhere.

./piku-bootstrap install-cli ~/bin
```

**Comment by chr15m** [comment]
@jsenin yes you will need to download the latest version of `piku-bootstrap` to use this feature.
