### ISSUE TITLE
Add a CONTRIBUTING doc and outline basic philosophy

### ISSUE THREAD

**Issue by chr15m** [piku/piku#134]
This could be useful to have in the README to point new contributors to.

@rcarmo do I have this right?

 * Runs on low end devices
 * ~1000 lines readable code
 * Functional code style
 * Few (single?) dependencies
 * [12 factor app](https://12factor.net)
 * Cover 80% of common use cases

Other potential values:

 * Sensible defaults
 * Simplify user experience
 * Leverage distro packages
 * Leverage standard tooling (git, ssh, uwsgi)
 * Backwards compatability where possible

**Comment by rcarmo** [comment]
Yep. That’s it. Feel free to nuke the bits of the README that don’t make sense, these days (and given travel, work and our time difference) I’m mostly keeping tabs on Piku via my phone...

**Comment by dwightmulcahy** [comment]
Yeah, I like that too since hearing that your overall (admirably) goal was to help make this accessible to hobbyists and K-12 schools.

**Comment by jsenin** [comment]
I suggest to add something about contributing like:
- small and focused pull requests. Don't add any other fix that your PR subject ( avoid extra refactors )
- use final imports,  Ej `from os.path import abspath`
- try to follow the main code style

**Comment by rcarmo** [comment]
@chr15m, since you picked this up I'm going to trim down the README to leave space for that, OK?

**Comment by rcarmo** [comment]
So I've just finished giving the README an initial pass, and just wanted to reference #144 from here.
