### ISSUE TITLE
Adding badges to README

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/piku#144]
What's the feeling about adding badges to the README file?

https://www.freecodecamp.org/news/how-to-use-badges-to-stop-feeling-like-a-noob-d4e6600d37d2/

**Comment by rcarmo** [comment]
I’m cool with it. I usually do that for Docker images, and think we should have one for tests (once we figure out how).

In fact, we should redo the README (I mean to do that by gathering some bits and pieces from other threads).

**Comment by rcarmo** [comment]
I also set up a kanban for the roadmap, which should be automatically updated when we handle issues.
