### ISSUE TITLE
More documentation on nginx ENV options

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/piku#145]
I have to admit I'm pretty light on nginx configuration.  Although it might/should be beyond the scope of this project to explain setting up nginx fully, I feel that the ENV variable usage should be expounded upon more.

So in all the examples, I don't see any usage of `NGINX_SERVER_NAME` how is that used?  Does this become your url for the app locally?
The only one I see is `NGINX_STATIC_PATHS=/static:static`.  I'm assuming that these are paths to static content (endpoints?) defined in the program?

Maybe expand those with a use-case so that usage of the options can be inferred?

**Comment by rcarmo** [comment]
Good point. Here’s a cut down version of my prod setup:

```
SERVER_NAME=taoofmac.com
DEBUG=False
HTTPS_ONLY=True
LANG=$LC_ALL
LC_ALL=en_US.UTF-8
NGINX_CLOUDFLARE_ACL=True
NGINX_SERVER_NAME=$SERVER_NAME
PYTHONIOENCODING=UTF_8:replace
TZ=Europe/Lisbon
UWSGI_LISTEN=128
UWSGI_LOG_X_FORWARDED_FOR=True
UWSGI_MAX_REQUESTS=256
UWSGI_PROCESSES=2
UWSGI_THREADS=2
```

**Comment by chr15m** [comment]
@dwightmulcahy just want to check you know about the [ENV document](https://github.com/piku/piku/blob/master/docs/ENV.md) - we probably need to surface this more clearly. One thing I've done in other README's is to put a nice bar of links near the top that go to the most pertinent info like:

[Install]() | [Examples]() | [ENV file]() | [Procfile]()

**Comment by dwightmulcahy** [comment]
Yeah @chr15m, the documentation is getting better for sure.  I've looked at the ENV doc but I think there is an assumption of deep (_then I have at least_) knowledge of nginx/uWSGI as a whole.

**Comment by rcarmo** [comment]
Reopening since this needs to get done.
