### ISSUE TITLE
Release Process for 1.0

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#146]
Picking up #25 and #130 (which are related), this is the issue where I'll rant about possible ways to automate the release - current plan is to:

- do a 0.9 for testing
- wrap up existing PRs
- tag 1.0 on master and cut the release

Then we move on to tackling #129 and break that down into steps (cleaning up core, etc.)

**Comment by dwightmulcahy** [comment]
Yeah, I like getting a 0.9 in with a testing framework in place.
