### ISSUE TITLE
Static apps that are running do not have an asterisk

### ISSUE THREAD

**Issue by chr15m** [piku/piku#151]
The change merged in #132 does not include apps which are deployed with a worker `static` (e.g. GitHub pages style static app deploys) so they show up in the apps list with no asterisk.

**Comment by chr15m** [comment]
To replicate:

 * Create a new folder called `piku-static-test`
 * Add an `index.html` with hello world.
 * Git add.
 * Add a `Procfile` with `static: /` as the only worker.
 * Deploy to your Piku box.
 * Do `piku apps` and observe the app has no asterisk.

**Comment by dwightmulcahy** [comment]
@chr15m hmmm, I'll take a look at it later.  Today is a travel day for me.

**Comment by jsenin** [comment]
Static workers do not use uwsgi, so we can't enumerate .ini files to determine if is working.

Using this seems to be the easiest way to check it for running, stop or destroy
```
        static = glob(join(NGINX_ROOT, '{}*.conf'.format(app)))
```

**Comment by jsenin** [comment]
We can use this approach to fix app list, stop and destroy and then, in a second round do some refactors.

**Comment by chr15m** [comment]
What about apps which just have a background worker and no web/static/wsgi workers? :thinking:

**Comment by rcarmo** [comment]
I'd say those need to have an asterisk as well, but maybe we just need to bite the bullet and list the workers/type in front of the app name in an "easy" way?

**Comment by dwightmulcahy** [comment]
Adding the workers could be  "verbose" mode?  Sometime like `piku app myapp` then it would display that info on the workers.

**Comment by chr15m** [comment]
Seems like what started as a simple UX change has ballooned into scope creep. Who would have predicted this would happen to a software project? :)

The main issue here is how do we define a "running" app?

At the moment you can't actually stop a static site, as the `stop` command only removes the uwsgi ini.

 * Web, wsgi, and background workers will all have a uwsgi ini, so the original solution works for them.
 * Static sites have an nginx conf but not a uwsgi ini so @jsenin's fix works for them, but it's complicated because non-static sites which have been stopped will also have an nginx config.

So there are a couple of things we could do:

 * Change the `stop` command so that it also removes nginx configs, and then use @jsenin's fix above to check for the presence of both nginx configs *or* uwsgi inis.
 * Change the asterisk output to have two modes. If there are uwsgi configs then show an asterisk, but if there is only an nginx config then show e.g. "s" so the user knows its static.

Probably a good idea for us to work out a definition for "stopped" in any case.

Perhaps we could fold `restart` and `deploy` into a single command which always removes both nginx and uwsgi configs, and `deploy` always creates them?

Thoughts?

**Comment by jsenin** [comment]
> Seems like what started as a simple UX change has ballooned into scope creep. Who would have predicted this would happen to a software project? :)
> 
> The main issue here is how do we define a "running" app?
> 
> At the moment you can't actually stop a static site, as the `stop` command only removes the uwsgi ini.
> 
> * Web, wsgi, and background workers will all have a uwsgi ini, so the original solution works for them.
> * Static sites have an nginx conf but not a uwsgi ini so @jsenin's fix works for them, but it's complicated because non-static sites which have been stopped will also have an nginx config.
> 
> So there are a couple of things we could do:
> 
> * Change the `stop` command so that it also removes nginx configs, and then use @jsenin's fix above to check for the presence of both nginx configs _or_ uwsgi inis.
> * Change the asterisk output to have two modes. If there are uwsgi configs then show an asterisk, but if there is only an nginx config then show e.g. "s" so the user knows its static.
> 
> Probably a good idea for us to work out a definition for "stopped" in any case.
> 
> Perhaps we could fold `restart` and `deploy` into a single command which always removes both nginx and uwsgi configs, and `deploy` always creates them?
> 
> Thoughts?

I like both, apply the same rule for all kind of apps, I mean delete ngnix and uwsgi files for stopping and find any ngnix or uwsgi files to consider as running. Also show the kind of app ( static, wsgi, front+wsgi, process...) its kindy info.
As an alternative, could be have something like a PID file to store the app state,  but maybe become more complex.

**Comment by rcarmo** [comment]
We already know the worker count for each app, so... why not use that to differentiate the output?

**Comment by dwightmulcahy** [comment]
if the worker count is used does that differentiate the type of app it is?  static vs running vs not running?

**Comment by chr15m** [comment]
@dwightmulcahy it doesn't.
