### ISSUE TITLE
Less stuff

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#155]
I've been looking at the repo structure and would like to make the core repo more approachable. I've been procrastinating on finishing #91 due to travel, #142 will target the README and #152 is in, so here are a few ideas:

* Finish #91, agree on #142 
* Keep only core docs (CONTRIBUTING.md, a single INSTALL.md) in the main repo
* Move detailed documentation to the website's repo (this is the one that will take the longest, I think)
* Move all other installation stuff (cloud-init, Ansible, etc.) to their own repos (so that we can set up tests for those as well)
* Have a reference plugin repo setup (we can use @jsenin's PG plugin as the core reference)

Thoughts?

**Comment by dwightmulcahy** [comment]
sounds like a good order to get everything in order.  ;)

**Comment by rcarmo** [comment]
Yep. I just churned out [deploy-on-azure](https://github.com/piku/deploy-on-azure) so that I can remove the `cloud-init` stuff. Tomorrow. :)

**Comment by chr15m** [comment]
@rcarmo very cool!
