### ISSUE TITLE
Does piku handle database like heroku?

### ISSUE THREAD

**Issue by tim-hub** [piku/piku#160]
or the db is required to deployed by user?

**Comment by rcarmo** [comment]
Hello there,

`piku` does not manage databases by itself. #129 is a first approach at building plugins to manage databases, but right now you should manage the database separately.

**Comment by chr15m** [comment]
@tim-hub you can get a database provisioned in your Piku project with very few steps.

First get a db installed on your instance. You can use this command once `piku-bootstrap root@yourserver postgres.yml` to do this if you have the bootstrap command locally.

Next in your project set a variable for the database name either in the `ENV` file or by setting a config var: `piku config:set DATABASE=mydb`

Finally add a script to your project to idempotently create the database if it does not exist already. I use this script:

```
#!/bin/sh
DATABASE=${DATABASE:-testdb}
psql "${DATABASE}" -c ";" 2>/dev/null && echo "Database ${DATABASE} already exists." || ( createdb "${DATABASE}" && echo "Database ${DATABASE} created." )
```

Add that as a `release` worker to your `Procfile`.

I will add some documentation about this and a demo project.

**Comment by tim-hub** [comment]
thanks
