### ISSUE TITLE
clojure.tools.deps support

### ISSUE THREAD

**Issue by den1k** [piku/piku#164]
https://github.com/piku/piku/pull/99#issuecomment-578188759

The Clojure community is split using both lein and Clojure.tools.deps. Tools.deps is the officially endorsed tool and from what I can see it marks a clear trend in the community. Could support be added for Clojure CLI and tools.deps?

[clojure.tools.deps](https://clojure.org/guides/deps_and_cli) guide

With Clojure CLI it’s not necessary to make an uberjar. However for that case: https://github.com/seancorfield/depstar

**Comment by matrixjnr** [comment]
I guess in most developments programmers prefer the best build tools.  `lein` and `boot` are still dominant and every time a new build support is added on top of a language support in Piku. Still a long way to go on refactoring the underlying algorithms without adding both language and build feature at the same time like Clojure-cli, Clojure-lein, Clojure-boot, Java-gradle, Java-mvn ...

I guess the `uberjar` feature helps use use the uwsgi java plugin in a way.

**Comment by den1k** [comment]
I have a consultancy mostly based in Clojure and we abandoned Leiningen in favor of tools.deps. I see many other projects do the same. Agree that the language and feature should be decomplected.

That said, if uberjar'ing is not needed, supporting tools.deps could be quite easy: check if there is a `deps.edn` file, make sure `clojure` cli is installed and run `clj -m main-namespace`. It would be great if this could be supported because deps and lein are not compatible unless one generates a `project.clj` from the `deps.edn` file.

**Comment by matrixjnr** [comment]
Alright, I will be testing that over the week.

**Comment by den1k** [comment]
@matrixjnr how is this going?

**Comment by matrixjnr** [comment]
I used `uberdeps` instead of `depstar` though I hate the part where I have to pass the main class to the `jar` file created.
But since we do not need an uberjar, I will create a pull request in the course of the day.

**Comment by chr15m** [comment]
@den1k note that you can already run any build task you like in a `release` worker, and then launch your server as a `web` worker passing in `$PORT`.

**Comment by den1k** [comment]
@chr15m that sounds promising. Is this considered a release worker? https://github.com/piku/sample-clojure-app/blob/master/Procfile

If not could you point me at an example that uses one.

**Comment by den1k** [comment]
@matrixjnr thanks for putting in the work. Happy to review/test this as soon as your PR is up.

**Comment by chr15m** [comment]
@den1k the file you linked has a web worker and you could use something similar to launch the main Clojure web service. Note that Piku sets the `PORT` environment variable to specify which port it should listen on.

For the release worker do something like this:

```
release: your-build-steps-command-line
web: your-web-worker-command-line
```

What I quite often do is put a script in `bin` which does the build tasks and then just have:

```
release: ./bin/release.sh
```

Hope this helps.

**Comment by chr15m** [comment]
@den1k so an example release script might be:

```
release: lein uberjar
```
