### ISSUE TITLE
Does piku support multiple web applications run from a single repository?

### ISSUE THREAD

**Issue by clusterfudge** [piku/piku#165]
I have a repo that has multiple services that communicate with eachother, and I'm wondering how I might specify the Procfile to use as metadata on the app.

**Comment by rcarmo** [comment]
By default (and for simplicity’s sake) piku only maps one web/wsgi worker to nginx, but you can have multiple services running and they can talk among themselves at will, so running servers on multiple ports is entirely feasible.

Can you provide more details on what you want to accomplish?

**Comment by clusterfudge** [comment]
Sure! I'm a contributor to https://github.com/MycroftAI/mycroft-core , and there's a couple different components that are all deployed out of the same repository. One component (messagebus) exposes a websocket server, and the other workers coordinate through it. I'm working on a new component that would also expose an HTTP service, so I'd need to be able to specify multiple HTTP ports for a single Procfile/app, or be able to have multiple procfiles/apps out of a single repository. 

Did any of that make sense? :P

**Comment by chr15m** [comment]
@clusterfudge I think you can simply put a line in the Procfile for each component and pass the details of ports etc. in to the command line invocation of the service.

**Comment by rcarmo** [comment]
Yes, that will work fine. The only real difference between a web: entry and a foo: entry is that we try to map it to nginx. As long as it's OK for the processes to expose HTTP ports directly, every process can do its own thing, there's no restriction except that we currently don't allow for nginx to proxy to more than one worker.
