### ISSUE TITLE
Bootstrap script should be able to be run on the destination machine

### ISSUE THREAD

**Issue by makbol** [piku/piku#166]
Hello. Thank you for bringing Piku to us! 

I have trouble with running Piku. I'm physically connected to RPi with mouse and keyboard. I tried `./piku-bootstrap pi@raspberrypi.local` then `./piku-bootstrap localhost` and `./piku-bootstrap 1.2.3.4` (where 1.2.3.4 is my IP address got from ifconfig) but none of them worked as I'm still getting 

```bash
./piku-bootstrap pi@1.2.3.4 nodejs.yml
Bootstrapping piku onto pi@1.2.3.4
Using built-in playbook: nodejs.yml

PLAY [all] ********************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
fatal: [pi@1.2.3.4]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: pi@1.2.3.4: Permission denied (publickey,password).", "unreachable": true}
	to retry, use: --limit @/home/pi/.piku-bootstrap/piku/playbooks/nodejs.retry

PLAY RECAP ********************************************************************************************************************************************
pi@1.2.3.4          : ok=0    changed=0    unreachable=1    failed=0
```

`unreachable=1 `

Worth noting that I'm behind proxy if that matters.

I'm not sure what I actually should put as `HOST` in that case.

**Comment by chr15m** [comment]
@makbol the bootstrap script is designed to be run from a local machine where you dev rather than on the destination server itself. It's probably possible to make it run on the destination server, because Ansible accepts the `--connection=local` flag, but currently the bootstrap script doesn't have that feature built in. I think we'd definitel merge a PR that allowed for that.

**Comment by makbol** [comment]
Thanks Chris. I think running script from dev machine (not RPi) is fine but what could be improved is documentation. Adding a little more clarification to the install process would be much helpful. Also I noticed that following only _Install_ section from `README.md` may be not enough for developers (not devops ppl) e.g. I was expecting running script like `./piku-bootstrap pi@1.2.3.4`  i got everything up and running but I needed to setup SSH keys, uwasgi etc

**Comment by chr15m** [comment]
> Adding a little more clarification to the install process would be much helpful.

This is great feedback, thank you. Can you let me know what path you followed through the documentation? e.g. "started with GitHub project page, clicked in 'docs', went to INSTALL.md" or maybe it was "visited piku.github.io, ran curl snippet" etc.

Good point about the SSH keys. You should not have to install uwsgi if you used the bootstrap script. Can you let me know what your exact target OS is?

**Comment by makbol** [comment]
TBH I went straight to _Install_ section and just scanned through looking for commands which would led me to install. When I noticed `curl https://piku.github.io/get | sh`  I immediately tried that one (I have experience with installing [nvm](https://github.com/nvm-sh/nvm#install--update-script) which has similar approach). For some reason I thought I need it to execute from RPi not dev machine itself. Maybe bc everywhere it's mentioned as a tool for RPi and it's not clear what's _local machine_ is. When it didn't work I started to fiddling around with `HOST` values (that's why I made this issue). Then I realised I need to execute from my dev machine and point to RPi IP address. Still could not get it through. After several minutes going back and forth I started to explore repo and by mistake I found `docs` folder. It helped but yet I wasn't sure if it's necessary or it's like backup plan if script won't work. After following steps up to setting SSH access I tried to run script and again got (don't remember exactly) some errors so I followed remaining steps. Did a test and looked it worked fine.

As it's pointed in [raspbian-9.4-stretch-10-buster.md](https://github.com/piku/piku/blob/master/docs/raspbian-9.4-stretch-10-buster.md) it's standalone instruction but for setting SSH keys you need to follow instruction first from INSTALL.md and then continue with _Setting up the piku user_ from  [raspbian-9.4-stretch-10-buster.md](https://github.com/piku/piku/blob/master/docs/raspbian-9.4-stretch-10-buster.md#setting-up-the-piku-user) which mentions 

> You will have to copy your ssh public key to the raspberry pi from your main system. If you already have sshd into your newly installed pi you can do the following

What for me means, after this sentence I'll get some commands to copy ssh public key to raspberry and it's ok if I'm already SSHd to RPi.

Also maybe adding a little command how to upload `id_rsa.pub` via scp from dev machine to RPi would be helpful and saved few minutes on googling :).

>Can you let me know what your exact target OS is?

Do you mean my dev machine or RPi? I'm working on Mac and I have RPi 2B running Raspbian Buster which is the device I tried to put Piku on.

I hope my descriptions helps. Tried to best to reproduce steps I took and point to some unclears from my perspective

**Comment by jguffey** [comment]
Just want to +1 this thread.

Installing Piku on a Raspberry Pi. I thought that the `piku-bootstrap` command was meant to run on the server, so I ssh'd into my rasp and installed it. I ran into the same problem as the original poster here, so I later found myself in [INSTALL.md](https://github.com/piku/piku/blob/master/docs/INSTALL.md) and [raspbian-9.4-stretch-10-buster.md](https://github.com/piku/piku/blob/master/docs/raspbian-9.4-stretch-10-buster.md). I thought that everything was installed correctly until I tried to push my first repo today and discovered that `virtualenv` isn't installed.

I think I can power through and get the environment up and running but I think it would be best to make clear the purpose of piku-bootstrap, is it meant to replace the instructions in INSTALL.md? I'd open a PR myself but I still don't know what I'm doing yet 🤪

**Comment by rcarmo** [comment]
Hi there. When doing a manual install you should have `virtualenv`, it’s listed here for both Python 2 and 3: https://github.com/piku/piku/blob/master/docs/raspbian-9.4-stretch-10-buster.md#dependencies

As to the bootstrap script, I’ll have to ask @chr15m to look into that. The vast majority of my `piku` installs these days is done via other means...

**Comment by toyg** [comment]
I'm having a similar experience. I see now that it says "on your local machine" a few times, but this is typically counter-intuitive when setting up a server-based thing like piku, so it still reads a bit ambiguous. Maybe it could use a bold paragraph clarifying that piku_bootstrap is _not_ meant to be run on the host where piku will run, but from a local laptop; and if I have to set up ssh keys in advance of provisioning the actual piku server, it should probably be stated upfront in the INSTALLING doc, rather than forcing the inevitable error.

**Comment by chr15m** [comment]
Will fix.
