### ISSUE TITLE
user management or team management

### ISSUE THREAD

**Issue by alizowghi** [piku/piku#169]
Hi
Is there any work on user management for deploying and managing apps?

**Comment by rcarmo** [comment]
No, but it can be done by adding/removing multiple SSH keys (which is probably best left to an external utility, since that kind of thing is usually done at a system-wide level by Puppet, Ansible, etc.)

Feel free to suggest approaches to this.

**Comment by alizowghi** [comment]
I handle user management with ssh key and installing piku in lxc for limit resources
But i think this is enough for now.

**Comment by chr15m** [comment]
:+1:
