### ISSUE TITLE
Problem in deploying python app

### ISSUE THREAD

**Issue by alizowghi** [piku/piku#170]
Hi
When I deploy python sample app [https://github.com/piku/sample-python-app](url) and set server name for nginx, I get 502 error
in log of nginx I have below errors:
`2020/03/12 12:40:30 [crit] 19007#19007: *21 connect() to unix:///home/piku/.piku/nginx/sample_python_app.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: piku.mydomain.com, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:///home/piku/.piku/nginx/sample_python_app.sock:", host: "piku.mydomain.com"`

and really there is not any socket for app.

**Comment by chr15m** [comment]
@alizowghi What does the `logs` command tell you e.g. `ssh piku@youserver sample_python_app logs`?

**Comment by abdulbasetbasher** [comment]
> Hi When I deploy python sample app [https://github.com/piku/sample-python-app](url) and set server name for nginx, I get 502 error in log of nginx I have below errors: `2020/03/12 12:40:30 [crit] 19007#19007: *21 connect() to unix:///home/piku/.piku/nginx/sample_python_app.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: piku.mydomain.com, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:///home/piku/.piku/nginx/sample_python_app.sock:", host: "piku.mydomain.com"`
> 
> and really there is not any socket for app.

did you fix it?
