### ISSUE TITLE
Worker persists after being removed from Procfile

### ISSUE THREAD

**Issue by chr15m** [piku/piku#173]
Steps to reproduce:

 * Add a worker to the `Procfile` and deploy.
 * Add a new worker to the `Procfile` and deploy.
 * Remove the first worker from the `Procfile and deploy.

The first worker will still be running in the logs. This is because `~/.piku/uwsgi-enabled/ORIGINAL_WORKER.1.ini` still exists. Where I saw this was transitioning from `web` worker to `wsgi` worker. Would be good to not have to destroy the app to accomplish this.

**Comment by chr15m** [comment]
Hm, maybe this isn't such a big deal. Setting `AUTO_RESTART=1` in `ENV` fixes this as it first deletes all .ini files for the app.

**Comment by rcarmo** [comment]
Well, I usually restart most new deployments because they introduce some kind of runtime change. It's tricky to have `piku` keep track of the state of each worker, that's what `uwsgi` does. I'm going to close this and make a note to add it to the docs.
