### ISSUE TITLE
MongoDB Playbook

### ISSUE THREAD

**Issue by nathankirk91** [piku/piku#175]
Hi,

Thank you so much for creating and sharing piku. It's really amazing. I was wondering, is it easy to write a playbook for MongoDB?

Nathan

P.S. also new to GitHub, so not sure if I'm posting this in the right area.

**Comment by evangineer** [comment]
The key thing is that you need to learn Ansible.

Putting together a MongoDB playbook was one of the first things I did when I started using Piku.

Using an existing MongoDB role sourced via Ansible Galaxy made it almost trivially easy.

**Comment by rcarmo** [comment]
I just set up `mongodb` via `cloud-init` (which I actually did yesterday on a fresh Piku deployment), so don't really see the relationship with Piku itself. Closing as is also a very old issue by now.
