### ISSUE TITLE
Rename Piku client

### ISSUE THREAD

**Issue by matrixjnr** [piku/piku#177]
I suggest renaming the piku client `**piku**` to be renamed piku-cli

**Comment by rcarmo** [comment]
@chr15m, what do you think?

**Comment by chr15m** [comment]
Hello @rcarmo! I don't fancy doing a bunch of work just so that I have to type more characters every time I interact with my Piku instance. Evidence of this being important to a bunch of other Piku users would probably be a good reason to do this. Failing that I would close as WNF.

**Comment by rcarmo** [comment]
Shell aliases would work just fine either way, so I have no firm opinion here (I don't use the CLI client anyway as I prefer to add `Piku` commands to project `Makefiles`).
