### ISSUE TITLE
Implications of installing piku

### ISSUE THREAD

**Issue by marcusique** [piku/piku#178]
The documentation states the following:

> **Warning:** You should use a fresh server or VPS instance without anything important running on it already, as piku-bootstrap will make changes to configuration files, running services, etc.

It would be great to add what configurations are affected by piku installation. I want to try to install it on a Raspberry Pi with WireGuard running as I don't have a separate environment for it and I'm not sure what exactly will happen.

**Comment by lordzpipo** [comment]
i have some issues with @marcusique ,
i try to install piku on fresh setup multipass instance, but no luck on it.

first install script told me i have no python, but python3 on my instance, 
what i do is alias python3 as python in my `.bashrc` and run again, then another new error is virtuanenv .
fine, install pip and get virtuanenv, and latest error as below:
```
#> Virtualenv setup not found. Installing it into /home/ubuntu/.piku-bootstrap.
 #> Setting up the virtual environment.
/usr/bin/env: ‘python’: No such file or directory
 #> Self-installation failed.
 #> Check /home/ubuntu/.piku-bootstrap/install.log for details.
./piku-bootstrap: 37: .: Can't open /home/ubuntu/.piku-bootstrap/virtualenv/bin/activate
```
need help on this

**Comment by lordzpipo** [comment]
> i have same issues with @marcusique ,
> i try to install piku on fresh setup multipass instance, but no luck on it.
> 
> at first, install script told me i have no python, but python3 on my instance,
> what i do is alias python3 as python in my `.bashrc` and run again, then another new error is virtuanenv .
> fine, install pip and get virtuanenv, and latest error as below:
> 
> ```
> #> Virtualenv setup not found. Installing it into /home/ubuntu/.piku-bootstrap.
>  #> Setting up the virtual environment.
> /usr/bin/env: ‘python’: No such file or directory
>  #> Self-installation failed.
>  #> Check /home/ubuntu/.piku-bootstrap/install.log for details.
> ./piku-bootstrap: 37: .: Can't open /home/ubuntu/.piku-bootstrap/virtualenv/bin/activate
> ```
> 
> need help on this

so after some research, 
solve with this few step:
1. install python3 if not exist in your system
2. add symlink to /sr/bin/env, if install script prompt python not exist: `sudo ln -s /usr/bin/python3 /usr/bin/python`

finally it works  😓

**Comment by curious-attempt-bunny** [comment]
Same here:

```
$ cat ~/.piku-bootstrap/install.log
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by curious-attempt-bunny** [comment]
How about this as a workaround?

```bash
sudo ln -s /usr/bin/python3 /usr/bin/python && curl https://piku.github.io/get | sh ; sudo rm /usr/bin/python
```

**Comment by chr15m** [comment]
@curious-attempt-bunny @lordzpipo are you installing onto an Ubuntu server?

**Comment by chr15m** [comment]
The documentation has now been updated.
