### ISSUE TITLE
How to get piku@server password

### ISSUE THREAD

**Issue by l2radamanthys** [piku/piku#179]
What is the default password for git in piku, how can I change it.

Install piku on a raspberry pi 3 b + with a clean install of raspberry py os, and it runs on a local network.

![2020-09-16_15-20](https://user-images.githubusercontent.com/125394/93376606-3a646c80-f830-11ea-8f3d-b718f4264fec.png)

**Comment by rcarmo** [comment]
Hello there. You’re supposed to use the SSH key as per instructions.

**Comment by l2radamanthys** [comment]
My SSH key doesn't work, I guess I need to add my public key on the server but I have no idea how.
The documentation does not say much about the subject in terms of the installation and configuration process.

**Comment by rcarmo** [comment]
Actually, it does:

https://github.com/piku/piku/blob/master/docs/ubuntu-18.04-bionic.md#setting-up-the-piku-user <https://github.com/piku/piku/blob/master/docs/ubuntu-18.04-bionic.md#setting-up-the-piku-user>

(the commands are not distro-specific)
