### ISSUE TITLE
Ability to alias multiple domains to a single piku app

### ISSUE THREAD

**Issue by chr15m** [piku/piku#181]
* [x] Update NGINX conf to allow multiple server names.
 * [x] Update acme.sh SSL certificate request to include multiple domains.

**Comment by rcarmo** [comment]
Something like `NGINX_SERVER_NAME=$SERVER_NAME1,$SERVER_NAME2`?

**Comment by chr15m** [comment]
@rcarmo I think Nginx will be fine already with space-separated domains as that is how the `server_name` Nginx config works. What needs to be updated is ordering the SSL domains.
