### ISSUE TITLE
Can you specify ports instead of 22?

### ISSUE THREAD

**Issue by rikusen0335** [piku/piku#182]
Title is it, for security reason, I changed ssh port to different one.

**Comment by rcarmo** [comment]
There is no need for any special handling. I use Piku on several hosts with non-standard SSH ports, you just add the port to the remote URL and git push as you would expect.

**Comment by rikusen0335** [comment]
Like, `./piku-bootstrap pi@someips`?

**Comment by rcarmo** [comment]
pretty much, yes. I add mine to `.ssh/config`, since I use short aliases for everything.
