### ISSUE TITLE
RaspberryPi 3 & Ubuntu Server 20.04 LTS installation issues

### ISSUE THREAD

**Issue by ehni** [piku/piku#183]
I stumbled into several issues trying Piku on a RaspberryPi 3 with Ubuntu Server 20.04 LTS and wanted to give some Feedback.

## Installation

* `python-pip` is not supported by Ubuntu Server 20.04 LTS anymore. I needed to manually remove this from the [playbook](https://github.com/piku/piku/blob/master/playbooks/piku.yml#L21).
* `uwsgi==2.0.15` is also causing issues (error message was the same as [this issue](https://github.com/unbit/uwsgi/issues/1220)), I just removed the fixed package so that the latest uwsgi is installed
* Running the `nodeenv.yml` playbook via `./piku-bootstrap user@host nodeenv` complained about missing privileges for `apt install`. I had to execute the playbook steps manually in the end as I had no idea how to fix this.
* Side note: running the `piku-bootstrap` from an Apple Silicon M1 chip didn't work. Virtualenv complained about a not compatible executable. Guess this is purely related to the new arm chip.

## How can I access deployed apps?

Now I have deployed the example nodejs app but how can I expose the application to access them in my network? I'm running the raspberry pi only in my local network and from the documentation I can't really figure out how I would be able to access deployed applications.

Running `curl localhost:<port-of-app>` on the raspberry pi returns e.g. the sample_node_js chat app index.html but I'm not able to access this page from e.g. my notebook. Do I need further configuration for this? Am I missing something?

**Comment by rcarmo** [comment]
Thanks for the feedback. I actually came across a few of those when updating [`deploy-on-azure`](https://github.com/piku/deploy-on-azure) the other day, and made a note to update the manual instructions when I have the time. @chr15m sort of owns the playbook, so I'm tagging him for follow-up as my break is ending today and I don't know when I'll find the time.

As to accessing your app, you _should_ be able to access `<your-pi-name.local>:<port-of-app>` from your machine, since Ubuntu 20.04 sets up `avahi` to announce `hostname.local` by default (I too have a few Pis running 20.04 on my LAN). If you can't, try explicitly setting a port number in the `ENV` file.

**Comment by ehni** [comment]
Thanks for the fast reply @rcarmo .

Still not working though :-( Looks like nodejs is only available on localhost and not exposed at all. See this logs: 
```shell
[robert@fedora sample-nodejs-app]$ git commit -m "Set port & listen to 0.0.0.0"
[master 3cefedb] Set port & listen to 0.0.0.0
 1 file changed, 1 insertion(+)
[robert@fedora sample-nodejs-app]$ git push piku master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 279 bytes | 279.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: -----> Deploying app 'sample_nodejs_app'
remote: HEAD is now at 3cefedb Set port
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: ['/usr/bin/nodejs', '/usr/bin/npm']
remote: -----> Checking requirements: ['npm']
remote: ['/usr/bin/npm']
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> nginx will look for app 'sample_nodejs_app' on 127.0.0.1:9999
remote: -----> letsencrypt certificate already installed
remote: -----> nginx will map app 'sample_nodejs_app' to hostname 'ubuntu'
remote: -----> Removing uwsgi configs to trigger auto-restart.
remote: -----> spawning 'sample_nodejs_app:web.1'
remote: -----> nginx will talk to the 'web' process via 127.0.0.1:9999
remote: -----> Releasing
remote: Hello!
```

From the raspberry:
```shell
ubuntu@ubuntu:/home/piku$ curl localhost: 9999
<content of index.html>
```

From my notebook:
```shell
me@mycomputer$ curl ubuntu:9999
curl: (7) Failed to connect to ubuntu port 9999: Connection refused
```

I then checked the ports on the Piku host:
```shell
ubuntu@ubuntu:/home/piku$ sudo lsof -i -P
nginx     12175        www-data    6u  IPv4  61958      0t0  TCP *:80 (LISTEN)
nginx     12175        www-data    7u  IPv6  61959      0t0  TCP *:80 (LISTEN)
nginx     12175        www-data   25u  IPv6 114432      0t0  TCP *:443 (LISTEN)
nginx     12175        www-data   26u  IPv4 114433      0t0  TCP *:443 (LISTEN)
nginx     12176        www-data    6u  IPv4  61958      0t0  TCP *:80 (LISTEN)
nginx     12176        www-data    7u  IPv6  61959      0t0  TCP *:80 (LISTEN)
nginx     12176        www-data   25u  IPv6 114432      0t0  TCP *:443 (LISTEN)
nginx     12176        www-data   26u  IPv4 114433      0t0  TCP *:443 (LISTEN)
nginx     12177        www-data    6u  IPv4  61958      0t0  TCP *:80 (LISTEN)
nginx     12177        www-data    7u  IPv6  61959      0t0  TCP *:80 (LISTEN)
nginx     12177        www-data   25u  IPv6 114432      0t0  TCP *:443 (LISTEN)
nginx     12177        www-data   26u  IPv4 114433      0t0  TCP *:443 (LISTEN)
nginx     12178        www-data    6u  IPv4  61958      0t0  TCP *:80 (LISTEN)
nginx     12178        www-data    7u  IPv6  61959      0t0  TCP *:80 (LISTEN)
nginx     12178        www-data   25u  IPv6 114432      0t0  TCP *:443 (LISTEN)
nginx     12178        www-data   26u  IPv4 114433      0t0  TCP *:443 (LISTEN)
nodejs    12181            piku   18u  IPv4 118792      0t0  TCP localhost:9999 (LISTEN)
```

Looks like the nodejs is not exposed at all and only available on the host itself. Rechecked all the logs and saw this entry when deploying the app `remote: -----> nginx BIND_ADDRESS set to 127.0.0.1`. After setting `BIND_ADDRESS=0.0.0.0` in the `ENV` it works now.

Not sure what I did wrong here. Will also check if this is an issue with other example apps as well.

**Comment by JSONJuggler** [comment]
@ehni speaking to your last bullet point, im also running into issues on the M1 chip. couldn't get virtualenv to work even after upgrades to pip3 and vitualenv itself

**Comment by rcarmo** [comment]
Closing this since it seems to be a configuration issue. `nginx` will only be bound to localhost if it's configured to do so, so this might be in `ENV`.
