### ISSUE TITLE
How to setup my own domain?

### ISSUE THREAD

**Issue by manuman94** [piku/piku#190]
Hi! 
Thank you for such as awesome work done with Piku!

I have installed it in my Raspberry Pi and I could push your example "sample-nodejs-app" successfully. I can access the APP using its local address specifying the APP port: 192.168.1.42:42156
(although I had to use the BIND_ADDRESS=0.0.0.0 in my ENV, without this it does not work)

I have a domain that points to my raspberry but I can't "link" the APP with it. I pushed the APP into Piku using ENV's value: NGINX_SERVER_NAME=mydomain.com ('mydomain.com' for example purposes, I put my actual domain) but when I visit my domain I get a 403 Forbidden.

In the deploy logs I get:
remote: -----> nginx will map app 'sample_nodejs_app' to hostname 'mydomain.com'
 ('mydomain' for example purposes, it specifies my actual domain)

Further, I can see in the access_log that I'm trying to access (so the domain is sure pointing to the raspberry).

It seems there is a problem with the mapping. I'm sure there is something I'm missing.

Thank you, greetings.

**Comment by rcarmo** [comment]
Hi there!

Is your DNS provider resolving `mydomain.com` to 192.168.1.42 at all? That would be the first thing to check.

The second is whether you've got this:

`
NGINX_CLOUDFLARE_ACL=False
NGINX_SERVER_NAME=mydomain.com
`

The ACL defaults to off, but you might have turned it on, and in that case it denies access from anything that is not a part of the Cloudflare network.

**Comment by chr15m** [comment]
@manuman94 another thing to check is if it tried to create an SSL certificate and failed somehow.
