### ISSUE TITLE
Deploy a dockerized app

### ISSUE THREAD

**Issue by krukkrz** [piku/piku#197]
I have an app that would usually be run with `docker-compose up` command. Is it possible to deploy it this way using piku?

**Comment by chr15m** [comment]
@krukkrz if you create a rule in the `Procfile` called `release` you should be able to put the docker command in there and have it run when you push. You might also like to check out [dokku](https://dokku.com/) which is geared towards Docker based deploys.

**Comment by krukkrz** [comment]
thanks @chr15m for a reply, it works :) 
I actually had to move to piku as I run it on raspberry pi
