### ISSUE TITLE
README needs deployment examples

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#199]
I've been cleaning out issues and I think we need to improve our deployment docs. The `README` spends a lot of time on install, but a lot of the questions in the issues are around setting hostnames, port mapping, etc.

So I've been thinking about rewriting it into separate `README`, `INSTALL` and `MANAGE` pieces, and also revisit the notion of moving all the installation stuff (like `piku-bootstrap`) onto a separate repo (like the `cloud-init` stuff). 

Then, once those are done, surface all of those docs on the GitHub Pages site, and link to that.

**Comment by chr15m** [comment]
> moving all the installation stuff (like piku-bootstrap) onto a separate repo (like the cloud-init stuff).

There is the [piku-bootstrap](https://github.com/piku/piku-bootstrap) repo in which I started doing this. What remains to be done is update the docs to use the new repository, and then remove the old scripts from this repo.

How does `cloud-init` work from a user perspective? Is there some tutorial I can follow? People seem to enjoy that `piku-bootstrap` is quick to get up and running.

**Comment by rcarmo** [comment]
`cloud-init` is very straightforward to use--you just need to submit the YAML file to your provider when you create a new VM, and it is supported on Digital Ocean, AWS, Azure, GCP, Oracle Cloud and the like. The [sample in the `deploy-on-azure` repo](https://github.com/piku/deploy-on-azure/blob/master/cloud-init.yml) actually works on all the above, plus or minus a couple of comments.

Typical user experience is that you get everything provisioned before you log in to the VM (although sometimes I need to tweak some things on a new provider), and it's been the way I've setup most of my recent instances.

Docs are [here](https://cloudinit.readthedocs.io/en/latest/index.html).

**Comment by skorokithakis** [comment]
I'm still struggling with this myself. I managed to deploy the app and can't for the life of me figure out the hostname to connect to so I can see it. Can anyone help? What am I missing? How are other people finding the hostname?

**Comment by chr15m** [comment]
@skorokithakis to connect from the outside world you will either need to set `BIND_ADDRESS` or `NGINX_SERVER_NAME` to the domain name you have pointed at the box.

**Comment by skorokithakis** [comment]
Thanks, @chr15m. I ended up abandoning Piku because I couldn't find a way to make it work without a TLS cert, which it couldn't get because it was a LAN-only installation and would never have access to the outside world.

**Comment by chr15m** [comment]
@skorokithakis understood, and thanks for the feedback. I have opened a new issue for deploying no-TLS sites.

**Comment by skorokithakis** [comment]
Thanks @chr15m, that would be great since a big use case for Piku for me would be deploying internal/home services on a Raspberry Pi.

**Comment by rcarmo** [comment]
FYI, I'm currently hosting all my home automation setup on a PI, and the "homepage" is a static HTML site that resolves under two names - a DNS alias provided by my ISP router, and an mDNS alias that the Pi itself announces.

My `ENV` looks like this:

```bash
SERVER_NAME=home.lan home.local
NGINX_SERVER_NAME=$SERVER_NAME
```

And my `Procfile`looks like this:

```bash
static: /
```

**Comment by skorokithakis** [comment]
Ah, so it will work even though I don't have one publicly-available name *per app*? That's useful to know, thanks! I'll try again, I can expose one name (though it'd be great if I didn't have to).

**Comment by rcarmo** [comment]
Yep. If you are using macOS/iOS or (some) Linux distros, you can get away with `.local` for a lot of stuff, since those clients will resolve `.local` and you can configure `avahi` on the Pi to announce multiple names on the LAN. 

You just can't use non-self-signed TLS with it.

**Comment by rcarmo** [comment]
As another example, I have `homebridge` set up like this:

`ENV`:

```bash
AUTO_RESTART=1
BIND_ADDRESS=0.0.0.0
PORT=1881
```
And`Procfile`

```bash
web: homebridge 2>&1 | cat
release: mkdir -p ~/.homebridge; cp -u config.json ~/.homebridge
```

This config does not go through `nginx` because there is no configuration set for it. But if I added `homebridge.local` as a name in the config (and made sure it was announced), `nginx` would take it up.

Note that in this case I'm setting `PORT` and `BIND_ADDRESS` for my own information, since `homebridge` reads those from its configuration file. But a normal Python or Node app would be able to read those values and bind to the right socket.

**Comment by skorokithakis** [comment]
Very useful, thanks! It would be great if examples like these were in the README, since they help a lot in understanding how to deploy various scenarios.

**Comment by rcarmo** [comment]
Yeah, That's something I've flagged as a `TODO` for myself. We thought the various example repos in the project would be more discoverable.

**Comment by rcarmo** [comment]
I've started writing a tutorial that can later (hopefully) be broken out into piecemeal examples:

https://github.com/piku/piku.github.io/blob/master/tutorial.md

I'm doing this in fits and starts (as usual), so contributions are welcome - the idea is that most of the examples, installation docs, etc., should actually move to the website ASAP.

**Comment by skorokithakis** [comment]
That looks excellent, I find the high-level explanation especially useful for understanding what the system does and how.

**Comment by rcarmo** [comment]
Reopening to make sure this stays on my TODO.
