### ISSUE TITLE
Piku doesn't install virtualenv on Raspbian

### ISSUE THREAD

**Issue by skorokithakis** [piku/piku#202]
I'm trying Piku out on my Raspberry Pi, and my first deployment failed because virtualenv wasn't installed. `sudo apt install virtualenv` fixed it, but I would have expected Piku to have installed that.

**Comment by rcarmo** [comment]
That is part of the manual setup instructions. How did you install it and what does `/etc/issue` say on your Pi?

**Comment by skorokithakis** [comment]
Ahh, okay, I didn't realize this was part of the "other dependencies", thank you.
```
stavros@raspberrypi ~> cat /etc/issue
Raspbian GNU/Linux 10 \n \l
```

**Comment by skorokithakis** [comment]
Actually, how do I do this? The only playbooks are:


```
root@raspberrypi:~# ./piku-bootstrap list-playbooks
java-openjdk.yml  piku.retry  piku.yml	postgres.yml
```

**Comment by rcarmo** [comment]
Paging @chr15m since I only do manual or cloud-Inuit installs these days.
