### ISSUE TITLE
Piku uses old `worker` directive

### ISSUE THREAD

**Issue by skorokithakis** [piku/piku#203]
I created a new app and specified a `worker` directive in the Procfile. Then I removed the directive and added a `wsgi` one, but the app fails to deploy because the worker directive won't work (even though it's not in the Procfile any more).

**Comment by rcarmo** [comment]
This is a corner case in which the `uwsgi` config files are generated once but not removed. You need to destroy the app prior to that kind of redeployment. It is “by design” in the sense that testing for that would somewhat add to the complexity of the main script.

**Comment by skorokithakis** [comment]
Hmm, what do you mean by "that kind"? This needs to at least be documented somewhere, as I don't know exactly what triggers it.

Why not just always regenerate the uWSGI config files, though? Wouldn't that be pretty quick?

**Comment by rcarmo** [comment]
It does regenerate them. It does not diff them, or check if there are changes in worker types.

**Comment by skorokithakis** [comment]
Oh hmm, I see. I'm not very clear as to how Piku works, I would imagine it would work if you just deleted the old file and regenerated everything, but it seems that there are problems with doing that.

Documenting which cases will lead to this problem and how to get around it would be good, though.
