### ISSUE TITLE
Incorrect broken version of piku-bootstrap is installed using the documentation

### ISSUE THREAD

**Issue by angordeyev** [piku/piku#206]
I try to install picu using [the documenation from piku repository](https://github.com/piku/piku/blob/master/README.md). It points to `curl https://piku.github.io/get | sh` which  gets the file from https://raw.githubusercontent.com/piku/piku-bootstrap/master/piku-bootstrap. 

Looks like [picu-bootstrap](https://github.com/piku/piku-bootstrap) repository has an  outdated duplicate of  piku-bootstrap. I think we have to remove duplicate files to avoid mismatch. Do we need a separate [picu-bootstrap](https://github.com/piku/piku-bootstrap) repository in case one of the goals for the application is to be minimalistic?

What do you think, should we move https://github.com/piku/piku.github.io/blob/master/get to the current repository as it is not related to the site?

**Comment by chr15m** [comment]
Hi @angordeyev. In #199 @rcarmo made clear he would like the bootstrap stuff to be in a separate repository, so I am working towards that. Sorry for the disruption while things change. I'm about to submit a PR that should hopefully clarify.
