### ISSUE TITLE
Gradle build not working

### ISSUE THREAD

**Issue by alperkal** [piku/piku#214]
The code part that triggers gradle build is actually running a maven build. This means although the gradle project is correctly detected, piku still runs a mvn command on the project, which usually fails.

problem is [here](https://github.com/piku/piku/blob/master/piku.py#L366) and [here](https://github.com/piku/piku/blob/master/piku.py#L364) while it should use [this](https://github.com/piku/piku/blob/master/piku.py#L395)

**Comment by rcarmo** [comment]
Thanks. We don't use Gradle much, obviously, so that code path wasn't being tested.
