### ISSUE TITLE
Invalid cron expression for a valid cron expression

### ISSUE THREAD

**Issue by chr15m** [piku/piku#216]
When I have a `Procfile` entry like this:

```
cron: 0 */3 * * * npm run update
```

I am getting the following error:

> Warning: misformatted Procfile entry 'cron: 0 */3 * * * npm run update' at line 2

There's a good chance I'm doing something stupid, but I'm filing an issue in case it's not me.

**Comment by rcarmo** [comment]
I’ll need to check the pre-validation before the slash gets converted to a uwsgi-friendly format. The Python sample app has a fixed 18 minute interval instead of a slash interval, will test with that.

**Comment by chr15m** [comment]
Thanks @rcarmo. I found another one too:

```
Warning: misformatted Procfile entry 'cron: 0 0 * * 1 nbb src/kpis.cljs' at line 1
```

**Comment by chr15m** [comment]
You probably saw this cron regex already: https://stackoverflow.com/questions/14203122/create-a-regular-expression-for-cron-statement

**Comment by rcarmo** [comment]
Well, we can't support all kinds of cron expressions since all I'm doing is translating to the uwsgi variant, but I'll whip up a few test cases that cover * and / use (those should work)

**Comment by rcarmo** [comment]
The plot thickens:

```python
from piku import CRON_REGEXP
from re import match

def test_cron_expressions():
    tests = [
        "cron: 0 */3 * * * npm run update",
        "cron:\t0 */3 * * * npm run update\n",
        "cron: 0 0 * * 1 nbb src/kpis.cljs",
        "cron: 0 0 18 0 0 foobar"
    ]


    for line in tests:
        kind, command = map(lambda x: x.strip(), line.split(":", 1))
        limits = [59, 24, 31, 12, 7]
        matches = match(CRON_REGEXP, command)
        print(command, matches)
        if matches:
            for i in range(len(limits)):
                if int(matches[i + 1].replace("*/", "").replace("*", "1")) > limits[i]:
                    raise ValueError
        print(command, "->", command.replace("*/", "-").replace("*", "-1"))

test_cron_expressions()
```

This outputs:

```
0 */3 * * * npm run update <re.Match object; span=(0, 26), match='0 */3 * * * npm run update'>
0 */3 * * * npm run update -> 0 -3 -1 -1 -1 npm run update
0 */3 * * * npm run update <re.Match object; span=(0, 26), match='0 */3 * * * npm run update'>
0 */3 * * * npm run update -> 0 -3 -1 -1 -1 npm run update
0 0 * * 1 nbb src/kpis.cljs <re.Match object; span=(0, 27), match='0 0 * * 1 nbb src/kpis.cljs'>
0 0 * * 1 nbb src/kpis.cljs -> 0 0 -1 -1 1 nbb src/kpis.cljs
0 0 18 0 0 foobar <re.Match object; span=(0, 17), match='0 0 18 0 0 foobar'>
0 0 18 0 0 foobar -> 0 0 18 0 0 foobar
```

...so it's not whitespace, nor the formatting itself... Weird. Have you checked that `Procfile` for any weird characters?

**Comment by chr15m** [comment]
Here's the Procfile: [Procfile.zip](https://github.com/piku/piku/files/7625998/Procfile.zip)
I get this error message:
```
remote: Warning: misformatted Procfile entry 'cron: 0 0 * * 1 nbb src/kpis.cljs' at line 1
```

**Comment by chr15m** [comment]
Ah, it's Python 3.5.

```
$ python3 crontest.py 
0 */3 * * * npm run update <_sre.SRE_Match object; span=(0, 26), match='0 */3 * * * npm run update'>
Traceback (most recent call last):
  File "crontest.py", line 25, in <module>
    test_cron_expressions()
  File "crontest.py", line 21, in test_cron_expressions
    if int(matches[i + 1].replace("*/", "").replace("*", "1")) > limits[i]:
TypeError: '_sre.SRE_Match' object is not subscriptable
```

When I run it under 3.6.9 it passes. Not sure if I want to upgrade the OS Python on my Ubuntu box just to support this feature.

**Comment by rcarmo** [comment]
Ah, ok. Most of my runtimes are now 3.8, and I didn't think back to whether there had been any changes in regex... well spotted!
