### ISSUE TITLE
Environment variables not being set (ENV is being ignored?)

### ISSUE THREAD

**Issue by knipknap** [piku/piku#218]
I am probably just doing something wrong, but I just can't manage to set an environment variable using Piku.
I created an ENV file:

```bash
$ cat ENV
CRYPTO_SALT=abcdefg
```
This has been committed to the master branch and pushed.

```bash
$ git commit -am "add ENV file for Piku"
...
$ git push piku master
...
```

However, this leads to the following traceback:

```bash
$ piku logs
Piku remote operator.
Server: piku@192.168.8.3
App: doorman-server

wsgi.1 |     from . import const
wsgi.1 |   File "./app/const.py", line 4, in <module>
wsgi.1 |     crypto_salt = os.environ['CRYPTO_SALT']
wsgi.1 |   File "/usr/lib/python3.9/os.py", line 679, in __getitem__
wsgi.1 |     raise KeyError(key) from None
wsgi.1 | KeyError: 'CRYPTO_SALT'
wsgi.1 | unable to load app 0 (mountpoint='') (callable not found or import error)
wsgi.1 | *** no app loaded. going in full dynamic mode ***
```

I also tried

```bash
$ piku config:set CRYPTO_SALT=abcdefg
```

But it didn't change the behaviour.

Any hints?

**Comment by rcarmo** [comment]
The usual troubleshooting steps are:

* Did you redeploy the app after pushing?
* What does `piku config:live` say?

**Comment by knipknap** [comment]
Thanks for the fast response! What do you mean my re-deploying after pushing, I thought that in Piku pushing is redeploying. Sorry if I understand the concept wrong. Interestingly, `piku config:live` shows the variable being set:

```
$ piku config:live | grep CRYPTO
Piku remote operator.
Server: piku@192.168.8.3
App: doorman-server

CRYPTO_SALT=abcdefg
```
And yet, Python does not see it. I also tried to `piku deploy`, with no change. 

However, now I tried `piku destroy` followed by pushing it fresh, from the repository and now it works! :-)

Thanks!

**Comment by rcarmo** [comment]
Ah, ok. So here's a tip: Pushing does not redeploy the running code, since you may want to do that for multiple apps in a row. You need to `piku restart`, which is effectively what you did by destroying it :)

**Comment by knipknap** [comment]
Ahhh, great, Thanks for the explanation!

**Comment by chr15m** [comment]
@knipknap please note that you can use the setting `AUTO_RESTART=1` which will give you the behaviour you expected.

**Comment by rcarmo** [comment]
We probably need to make that the default.

**Comment by rcarmo** [comment]
I just did that. Also changed it to `PIKU_AUTO_RESTART` and changed some internal `ENV` variable names because they might collide with other things.
