### ISSUE TITLE
nginx config not created

### ISSUE THREAD

**Issue by knipknap** [piku/piku#219]
For some reason, my Flask app is not made available through nginx; Piku seems to not update the nginx config. Here's what I did: First, I pushed the code to the Raspberry running Piku:

```
$ git push piku master
Enumerating objects: 124, done.
Counting objects: 100% (124/124), done.
Delta compression using up to 20 threads
Compressing objects: 100% (116/116), done.
Writing objects: 100% (124/124), 120.75 KiB | 9.29 MiB/s, done.
Total 124 (delta 49), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (49/49), done.
remote: -----> Creating app 'doormanhub'
[...]
remote: -----> picking free port 47681
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> spawning 'doormanhub:wsgi.1'
remote: -----> nginx will talk to uWSGI via 127.0.0.1:47681
To 192.168.8.3:doormanhub
 * [new branch]      master -> master
```

After that, the WSGI server is running and on the Raspberry I can reach it:

```
pi@raspberrypi$ curl 127.0.0.1:47681
<!doctype html>
[...]
```

However, I can not reach it through nginx, since there is no config that maps it to the uwsgi server.
The global file contains a reference to the home dir:

```
pi@raspberrypi$ grep -R .piku /etc/nginx/sites-enabled/
/etc/nginx/sites-enabled/default:include /home/piku/.piku/nginx/*.conf;
```

But this directory is empty:

```
pi@raspberrypi$ ls -l /home/piku/.piku/nginx/
total 0
$
```

What am I missing?
For reference, here is my Procfile:

```
$ cat Procfile 
wsgi: app.hub:app
$
```

**Comment by rcarmo** [comment]
Have a look at [the Python sample app](https://github.com/piku/sample-python-app) and see if you're missing a setting. I typically set `PORT`, for instance, but try comparing both apps.

Also, what version of Raspbian, out of curiosity? These things are hard to reproduce on our end because sometimes the package defaults change between distributions, and the original assumptions that `Piku` follows are outdated.

**Comment by rcarmo** [comment]
Oh, and you don't seem to have a hostname set, either. Try setting `NGINX_SERVER_NAME` to `raspberrypi.local` (or `.lan`, whatever your local DHCP/DNS hands out)

**Comment by knipknap** [comment]
Thanks again for the fast response - setting NGINX_SERVER_NAME resolved that problem.
For the record, here is the version info:

```
piku@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
piku@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
piku@raspberrypi:~ $ 
```

(It still doesn't entirely work however, it then failed because ~/.piku/acme/ didn't exist. After creating that manually, it is missing a doormanhub.crt file.) Anyway, I am closing this issue because the others are unrelated.

Thanks again!

**Comment by rcarmo** [comment]
Thanks! Well, at least now we know bullseye doesn't break anything :)

**Comment by chr15m** [comment]
@knipknap is probably running into #212.
