### ISSUE TITLE
incron is deprecated in Debian bullseye - need systemd.path replacement

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#220]
As I was expanding the automated test ranges, I discovered that `incron` has been removed from Debian 11. 

There is a possible workaround using [a custom `systemd.path` unit](https://www.freedesktop.org/software/systemd/man/systemd.path.html), but I have exhausted my time window to pursue that. 

(Should be a great first issue for someone and would also be back-portable to all the other distros)

**Comment by chr15m** [comment]
Wow, I did not expect incron to be deprecated. Do you have a link to where I can read about that?

**Comment by rcarmo** [comment]
The package is not shipping with bullseye, and is only listed for older releases: https://packages.debian.org/search?keywords=incron

I saw mentions of it being moved to `inotify-tools`, but the `bullseye` package contents don't lest that executable, and it appears that [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947425) has been open since 2020 and thus it missed the window to be included in `bullseye`.

**Comment by chr15m** [comment]
I wonder how many servers will break when they upgrade. https://qa.debian.org/popcon.php?package=incron

**Comment by eriol** [comment]
@chr15m incron was removed because of the bug mentioned by @rcarmo https://tracker.debian.org/news/1096817/incron-removed-from-testing/
The same bug was reported upstream https://github.com/ar-/incron/issues/36 but it seems that incron is not maintained anymore (last commit in 2017).

**Comment by thompol** [comment]
@ar- are you still maintaining incron?

**Comment by timhuebener** [comment]
I'm interested in setting up [a custom systemd.path unit](https://www.freedesktop.org/software/systemd/man/systemd.path.html) 😄 

I already had a look into it and I hope it should not be too much of a problem 😅  (I know always a risky statement)

**Comment by timhuebener** [comment]
draft PR is up

**Comment by chr15m** [comment]
@timhuebener thanks for this, the patch looks good and concise. I will test it out this week on a spare box.

One thing: could you add the `nginx.path` file to the PR so that later we can change the referenced location to the actual piku repo?

**Comment by rcarmo** [comment]
Just came back to check on this, have been busy. Can't see the PR, might have a box to check it out.

**Comment by timhuebener** [comment]
@chr15m I just added the files 

@rcarmo here is the PR https://github.com/piku/piku-bootstrap/pull/3

**Comment by chr15m** [comment]
@rcarmo we could move the system files into the main piku repo if you want them there instead.

**Comment by rcarmo** [comment]
Yeah, that would be great, since that’s where everything else is right now. Let’s test first.

**Comment by chr15m** [comment]
Bumping this so it doesn't get closed. See piku/piku-bootstrap#3 for progress.

**Comment by rcarmo** [comment]
Looks good, thanks! Also seems to have triggered a failure in the automated tests since `click` has moved beyond OS packages, but that's already tracked in #236

**Comment by Jibun-no-Kage** [comment]
So that is the final state?  I still do not see incrond in the repo for bullseye?

**Comment by thompol** [comment]
I suspect incron is just dead. I have rewritten several guides and scripts to use systemd, see https://forum.howtoforge.com/threads/securing-the-control-panel-with-a-lets-encrypt-certificate-when-using-acme-sh.86950/ for a example.

**Comment by Jibun-no-Kage** [comment]
Yes, although I found the source and instructions to compile it, on the i-notify web site, it does seem like it has not been updated for some time.  Thanks for the reply, and suggestion.  I had a real simple use case, quite easy to adapt other methods.

**Comment by rcarmo** [comment]
We’re not going to support `incron` going forward. There are only a few spots left to clean up in the docs regarding that (and I have to update some of the install instructions), but given Debian dropped it, we can’t rely on it being there for users…
