### ISSUE TITLE
which branch gets deployed?

### ISSUE THREAD

**Issue by tcurdt** [piku/piku#221]
From the docs it's not quite clear which branch actually gets deployed.
Would be great to add this to the README.
Or did I just miss that part of information?

**Comment by rcarmo** [comment]
It's the default one regardless of whether you use `main` or `master`. I have both kinds of apps deployed.

**Comment by tcurdt** [comment]
Often the default branch isn't the release branch. Would be nice if it was possible to specify a different branch.

**Comment by rcarmo** [comment]
that is a trivial thing to do like so:

```bash
git push release-branch-name production-server:master
```

**Comment by tcurdt** [comment]
Ah, I didn't think of that way. That should go into the docs as a hint. Thanks!

**Comment by chr15m** [comment]
My understanding was whatever branch you are currently on (local) gets deployed. So you can push any branch like this:

```
git checkout some-branch
git push piku master
```
