### ISSUE TITLE
laravel example

### ISSUE THREAD

**Issue by tcurdt** [piku/piku#222]
Would be great to have an example for a PHP Laravel app. Seems like another popular use case.

**Comment by rcarmo** [comment]
Currently we do not support PHP. `uwsgi` has a `php` plugin, so it should be easy to add, but AFAIK none of the current committers/contributors are PHP developers, so we don't have an easy way to iterate on that.

**Comment by tcurdt** [comment]
Thanks for the quick response. I am not really a PHP dev either. But I have a PHP project I need to deploy and `piku` looked intriguing. Feel free to track it as feature request.

**Comment by rcarmo** [comment]
Notes for future reference:

* There is a likely way to implement this by generating a worker config file according to [this section in the docs](https://uwsgi-docs.readthedocs.io/en/latest/PHP.html). 
* Not sure how this will play with distro packages.

**Comment by chr15m** [comment]
@rcarmo a different strategy could be for us to supply example `release` worker scripts showing how to deploy for other platforms like PHP. We could even move some of the built-in release methods out into these type of release scripts. :thinking:

**Comment by EpicVoyage** [comment]
Just in case anybody ends up here, pull request #369 allows Laravel to run on Piku.
