### ISSUE TITLE
How to install within Docker container?

### ISSUE THREAD

**Issue by ktonegawa** [piku/piku#223]
Hi there, just a note in advanced I am still very new to Docker and dont have a clear understanding of what I am doing.

I am wanting to install this within in actual Docker container as a way to separate this from everything else in my system.

I am running **Ubuntu 20.04 on a Raspberry Pi 3 Model B(?)** and creating a Docker image via this dockerfile:

```
# testing a custom Dockerfile to create an image i want

FROM ubuntu:20.04
# this thing below is to get rid of the timezone error bs
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    vim \
    openssh-server \
    curl
RUN mkdir /var/run/sshd
RUN echo 'root:mypassword' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```

I then create the Docker container within this image with:
`sudo docker run -d -P --name test_sshd_container sshd_tagged_image`

And I enter the bash of this container:
`sudo docker exec -it test_sshd_container bash`

 And i try to install to install Piku via `curl https://piku.github.io/get | sh` and running `./piku-bootstrap install` after that, but it always seems to fail with this message

```
TASK [Copy authorized_keys from root] ******************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find or access '~/.ssh/authorized_keys' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

I thought its simply because this `~/.ssh/authorized_keys` file didnt exist, so i just do a copy of the rsa_key.pub file:
`cp /etc/ssh/ssh_host_rsa_key.pub ~/.ssh/authorized_keys`

and I run this again and then i get this error:

```
TASK [Gathering Facts] *********************************************************
fatal: [127.0.0.1]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "/bin/sh: 1: sudo: not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}}, "msg": "The following modules failed to execute: setup\n"}
```

So i really dont know what is happening at this point, and seems like the `cloud-init` method install for containers does not work.

So ultimately I'd like to ask if installing this is even possible in a Docker container and if so how do I go about doing this properly?

**Comment by rcarmo** [comment]
Hi there!

`cloud-init` does not exist in most base containers, and is not really designed to work there. You need to build your own image and run the individual installation commands inside a `Dockerfile`.

I have done that before, but running a full system inside a Docker container will be tricky since you have no `init` and would need to start `nginx`, `incron` and `ssh` yourself-which would be kind of against the “single process” ethos of Docker.

If you just want isolation and an easier way to run things that feels like a VM, I would recommend looking at LXD instead, which will run multiple daemons inside a “machine” container and will run `piku` correctly (that’s how I test it occasionally).

**Comment by ktonegawa** [comment]
Hello there, thank you for your response.

So does that mean technically it is possible to install on a Docker container even though it may not have the "simplicity" in terms of what services/packages to enable? If so how would I go about doing this?

I was following this guide but it seems to be somewhat outdated, at least it seemed to fail on me when trying to install Java on a normal Ubuntu 20.04 LTS OS (also on a Raspberry Pi 3)...
https://github.com/piku/piku/blob/master/docs/INSTALL.md

**Comment by rcarmo** [comment]
There is a (pretty much dead) stab at doing that in https://github.com/piku/docker-debian. 

My key point Is that it just didn’t make any sense to use or deploy piku in that way given the added complexity and the fact that Docker is designed to run single processes, whereas piku is actually composed of multiple processes and designed to manage them via wsgi.

You can use that as a base, but you will need to update it and include an init system to run all the daemons.

**Comment by chr15m** [comment]
@ktonegawa there is a project similar to Piku which is explicitly designed for Docker deployment: https://dokku.com/
