### ISSUE TITLE
Bump requirements to 3.8

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#227]
Since Python 3.5 just got dropped from the GitHub Actions test suite, I'm thinking of bumping the minimal Python version requirement to 3.8 (which seems like the baseline for current Linux LTS distros, although I think Debian was doing their own thing).

Comments?

**Comment by chr15m** [comment]
Python's aggressive upgrade cycle and backwards incompatible language changes really rub me up the wrong way. Contrast with e.g. Clojure, Node, C, where code I wrote 10 years ago still runs fine. I suppose there's not much we can do about that barring rewriting on a different runtime (don't tempt me lol) or coding defensively and avoiding new language features unless forced to.

Anyway, that's my preference - creating less work not more.

**Comment by rcarmo** [comment]
yeah, well, I'm thinking of re-doing this in Go, to be honest. But doing that would lose a few features we get for free with `uWSGI`, so right now targeting 3.8 and issuing warnings below seems like the least effort approach.

**Comment by chr15m** [comment]
What about cljs packaged up with [nexe](https://github.com/nexe/nexe)? It seems like [nbb](https://github.com/borkdude/nbb) would be a perfect fit for this. Could ship single-file cross platform builds like Go.

**Comment by chr15m** [comment]
I would be happy to swap out `uWSGI` with user mode systemd and path watchers. Maybe this should be a totally separate project though. :thinking:

**Comment by rcarmo** [comment]
Reopening this (it was auto-closed) and tagging @ewalk153 here for visibility. Like I wrote in the `README` a while back, I’d like to move this up to align with current LTS distros (Ubuntu 22.04 and Debian 11, both of which are now way past Python 3.5). 

I suggest we snapshot `piku.py` into a “legacy” folder, change the `.format()` calls to f-strings (which will actually be more readable) and move on to “ship” a 1.0 that uses modern Python and `click` versions without hacks.

> In the meantime I have been considering using `caddy` as a combined proxy/supervisor, and that might be a nice way to go for 2.0/`piku2`, but that would mean going for something like Go and losing a lot of the simplicity and ability to hack in new features (the caching stuff I added over the holiday makes me think the Python approach has _miles_ to go yet), so it might indeed actually be a different project, and not necessarily a more useful one…

Thoughts?

**Comment by ewalk153** [comment]
I don't see any major [benefits to 3.8 syntax over 3.7](https://docs.python.org/3/whatsnew/3.8.html). Maybe the only marginal improvement is self documenting expressions in f-strings:
```python
>>> user = 'eric_idle'
>>> member_since = date(1975, 7, 31)
>>> f'{user=} {member_since=}'
"user='eric_idle' member_since=datetime.date(1975, 7, 31)"
```

If we want to fold in this syntax, I'll, drop the OS docker images reliant on 3.7 based on this PR: https://github.com/piku/piku/pull/263

+1 to snapshot the current `piku.py` and move to ship a 1.0 using the latest Python and `click` features without hacks. That should enable the `piku.py` to remain evergreen with the least amount of maintenance. The snapshot provides an option for anyone locked to an older version of python.

Not enough experience with caddy to weigh in on piku2.

**Comment by rcarmo** [comment]
Closing this as we have since settled on 3.7.
