### ISSUE TITLE
Piku reports app as "not deployed" if no env vars have been configured

### ISSUE THREAD

**Issue by chr15m** [piku/piku#234]
In the case where an app has env vars configured in it's own `ENV` file but the user has not done any `config:set`, Piku reports the app as not deployed:

```
$ piku config
Piku remote operator.
Server: piku@piku.mccormickit.com
App: rogule

Warning: app 'rogule' not deployed, no config found.
```

The correct behaviour should be to say "no config set" or perhaps to merge the local ENV file when displaying the config. Saying the app is not deployed is somewhat misleading.

**Comment by dwightmulcahy** [comment]
Why not create an empty (or just comments) `ENV` file?   Hacky, but would bypass this error.

**Comment by rcarmo** [comment]
Reopening this since it bugs me that some issues were auto-closed. This one can be confusing to new users.
