### ISSUE TITLE
Procfile: misformatted cron entry

### ISSUE THREAD

**Issue by rphenriques** [piku/piku#237]
Hi, 

I have a Procfile that looks like this:
`cron: 0 11 * * 7 python3 run_all.py`
(also tested cron: 0 11 * * 7 python run_all.py)

I get this error when pushing:
(...)
```
remote: Warning: misformatted Procfile entry 'cron:1' at line 0
remote: -----> Removing uwsgi configs to trigger auto-restart.
remote: -----> spawning 'testing-cron-procs:cron.1'
remote: -----> uwsgi scheduled cron for 0 11 * * 7 python run_all.py
```
(...)

the host for piku is running Python 3.8.10, running on Ubuntu 20.04.4 LTS on aarch64

Cron does no run, but if Procfile has 
`worker: python run_all.py`

it runs after pushing without issues. (cron still does not run)

**Comment by chr15m** [comment]
@rphenriques thanks for posting this issue. :+1:

**Comment by rcarmo** [comment]
Just checking here: You want your script to only run at 11 AM on Sundays? 

That's quite specific, and takes a week to test for.

Have you tried setting up a test task to run every few minutes and check that it is running?

**Comment by rphenriques** [comment]
Hi, yeah, sorry, bad example. In the end I'll want something like that but I did try setting it up to the day I was in, just some minutes ahead, but same result.

**Comment by rcarmo** [comment]
I think that is due to the limit check in https://github.com/piku/piku/blob/master/piku.py#L270 - I'm testing if 7 > 7, which is of course wrong, but would explain what you're seeing. Just edit that limit to be an 8 in piku.py while I figure out a saner way to validate...

**Comment by rcarmo** [comment]
Ok, no. The check is actually working OK, but I can't reproduce this with the line you provided:

```
>>> from re import match
>>> CRON_REGEXP = "^((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) (.*)$"
>>> line = "cron: 0 11 * * 7 python3 run_all.py"
>>> kind, command = map(lambda x: x.strip(), line.split(":", 1))
>>> command
'0 11 * * 7 python3 run_all.py'
>>> limits = [59, 24, 31, 12, 7]
>>> for i in range(len(limits)):
...   if int(matches[i].replace("*/", "").replace("*", "1")) > limits[i]:
...     print(i, limits[i]) # this should complain
... 
>>> hmmmmm.
```

Could there be a tab or other kind of weird character in your `cron` line?

**Comment by rphenriques** [comment]
Just tested it again. Created new Procfile with nano and typed the cron line. I changed the date and the error keeps. But this time the cron ran OK on the expected timing. (and yes, sorry, I realised the day 7 on cronfile is not standard)

Not sure if you want to keep this issue open or close it.

```
remote: -----> Python app detected.
remote: Warning: misformatted Procfile entry 'cron:1' at line 0
remote: -----> Removing uwsgi configs to trigger auto-restart.
remote: -----> spawning 'job-saphety:cron.1'
remote: -----> uwsgi scheduled cron for 15 13 * * 3 python3 run.py
```

**Comment by chr15m** [comment]
@rphenriques could you upload your exact `Procfile` somewhere?

**Comment by chr15m** [comment]
@rphenriques can you also `update` your `piku.py` by using `piku update`? If you don't have the `piku` local CLI you can use ssh to run the update command instead.

@rcarmo I think there are two issues here:

1. We should test/fix that crons run even if there is no other line in the Procfile, similar to what we did for static.
2. This cron misformatting thing which could be due to an older `piku.py` - will see how @rphenriques goes with an update.

**Comment by rphenriques** [comment]
Hi @chr15m Thanks! Yes, Ive updated '''piku''' just before I made my last comment. Did it again now and no updates, so it should OK. 

My file is here: https://transfer.sh/KrCOF2/Procfile1.txt

But apparently it could be something on my side. On another project I used the file: https://transfer.sh/ypHG8T/Procfile2.txt (which is quite similar, as you can see) and it went OK. Now I have copied this file to the other project and the warning went away. Strangest thing is I created the one with the warning by scratch and both files reported as being "Procfile: ASCII text".

**Comment by chr15m** [comment]
@rphenriques that is indeed strange. I notice the order of the lines is reversed. If you swap the first and second line in `Procfile1.txt` does it fix the issue?

**Comment by rcarmo** [comment]
Hi there. Maybe check the encoding on those files as well? Wouldn’t be the first time I’ve come across non-whitespace blanks in UTF-8.

**Comment by rcarmo** [comment]
I figured it out. It was a long-standing off-by-one issue

**Comment by chr15m** [comment]
Great, but did we patch it?
