### ISSUE TITLE
Update acme.sh

### ISSUE THREAD

**Issue by Noonlord** [piku/piku#242]
Hi! I tried to use default acme.sh to get a lets encrypt certificate but it didn't work. I tried updating from the official repo and it started working. Also I needed this: https://github.com/piku/piku/pull/240

**Comment by chr15m** [comment]
Thanks for reporting this, will fix in piku-bootstrap.

**Comment by Noonlord** [comment]
> 

So, I realized that even after updating that, it still is not able to get a certificate.

`remote: [Thu May  5 13:39:24 UTC 2022] testap.noonlordhost.com:Verify error:130.61.19.44: Invalid response from http://testap.noonlordhost.com/.well-known/acme-challenge/2wU_IhhzcVK20NsXAYXdnKRZWrFxUGru49ccOse-WDc: 404
remote: [Thu May  5 13:39:24 UTC 2022] Debug: get token url.
remote: [Thu May  5 13:39:24 UTC 2022] GET
remote: [Thu May  5 13:39:24 UTC 2022] url='http://testap.noonlordhost.com/.well-known/acme-challenge/2wU_IhhzcVK20NsXAYXdnKRZWrFxUGru49ccOse-WDc'
remote: [Thu May  5 13:39:24 UTC 2022] timeout=1
remote: [Thu May  5 13:39:24 UTC 2022] _CURL='curl --silent --dump-header /home/piku/.acme.sh/http.header  -L  -g  --connect-timeout 1'
remote: <html>
remote: <head><title>404 Not Found</title></head>
remote: <body>
remote: <center><h1>404 Not Found</h1></center>
remote: <hr><center>nginx/1.18.0 (Ubuntu)</center>
remote: </body>
remote: </html>
remote: [Thu May  5 13:39:24 UTC 2022] ret='0'
remote: [Thu May  5 13:39:24 UTC 2022] Debugging, skip removing: /home/piku/.piku/acme/.well-known/acme-challenge/2wU_IhhzcVK20NsXAYXdnKRZWrFxUGru49ccOse-WDc`

here is an acme log

**Comment by chr15m** [comment]
Can you let me know how you installed (bootstrap script?) and which OS and version you installed on. I will try to replicate.

**Comment by Noonlord** [comment]
Well, after creating a new app it just worked for some weird reason. For automated SSL to work it just needs https://github.com/piku/piku/pull/240 and latest acme.sh that's all
