### ISSUE TITLE
Node.JS app just not deploying?

### ISSUE THREAD

**Issue by kinostl** [piku/piku#243]
I have Piku installed and it acts like its deploying, and gives me this output. I can't actually see that port being used when I do lsof -i:port

```
minty@mio:~/roughdrafts$ piku deploy
Piku remote operator.
Server: piku@roughdrafts.xyz
App: roughdrafts

-----> Deploying app 'roughdrafts'
-----> Node app detected.
-----> Checking requirements: ['nodejs', 'npm']
[None, '/usr/bin/npm']
-----> Checking requirements: ['node', 'npm']
['/usr/bin/node', '/usr/bin/npm']
-----> Checking requirements: ['npm']
['/usr/bin/npm']
-----> picking free port 55765
-----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
-----> nginx NGINX_IPV6_ADDRESS set to [::]
-----> nginx BIND_ADDRESS set to 127.0.0.1
-----> nginx will look for app 'roughdrafts' on 127.0.0.1:55765
-----> letsencrypt certificate already installed
-----> nginx will map app 'roughdrafts' to hostname(s) 'roughdrafts.xyz'
-----> nginx will redirect all requests to hostname(s) 'roughdrafts.xyz' to HTTPS
-----> Removing uwsgi configs to trigger auto-restart.
-----> spawning 'roughdrafts:web.1'
-----> nginx will talk to the 'web' process via 127.0.0.1:55765
```
My procfile is this

```
web: npm run deploy
```

and heres the relevant parts of my package.json

```
  "scripts": {
    "dev": "PORT=3000 node -r dotenv/config .",
    "test": "jest",
    "predeploy": "prisma migrate deploy && npm run updatePrismaClient",
    "updatePrismaClient": "npm install --package-lock=false --prefix $(echo $NODE_PATH)/.. @prisma/client",
    "deploy": "node ."
  },
```

If I do `piku run npm run deploy`, it works. Connects to the port and nginx is all happy. I'm out of ideas.

**Comment by Noonlord** [comment]
Did you check logs with  `ssh piku@roughdrafts.xyz logs roughdrafts `? And change your Orocfile to this to see more `web: npm run deploy 2>&1 | cat
`

**Comment by kinostl** [comment]
Just tells me `No logs found for app 'roughdrafts'.` which is weird cause on my local the server is very verbose.

**Comment by chr15m** [comment]
It looks like it's using your system version of `node`, which might be old or out of date. Try adding a specific node version to your ENV file like this:

```
NODE_VERSION=16.13.1
```

Set it to be the same version as you are using locally. You can check that locally with `node --version`.

**Comment by kinostl** [comment]
System version of node is `v18.1.0` I actually swapped to it cause nodeenv wasn't able to use its own npm for some reason.

**Comment by chr15m** [comment]
When you changed the Procfile to `web: npm run deploy 2>&1 | cat ` I presume you did a `git push piku` and not just a `piku deploy`.

**Comment by kinostl** [comment]
Correct.

**Comment by chr15m** [comment]
`No logs found for app 'roughdrafts'.` this is actually a bit strange because I think it should at least create the logfile. Hmmm.

If you do `piku shell` and then `npm run deploy` what is the output from the server?

**Comment by chr15m** [comment]
And just to be sure what does `piku run node --version` do?

**Comment by kinostl** [comment]
```
minty@mio:~/roughdrafts$ piku run node --version
Piku remote operator.
Server: piku@roughdrafts.xyz
App: roughdrafts

Usage: piku.py run [OPTIONS] APP [CMD]...
Try "piku.py run --help" for help.

Error: no such option: --version
```

**Comment by chr15m** [comment]
Sorry `piku run node -- --version`

**Comment by kinostl** [comment]
```
minty@mio:~/roughdrafts$ piku run node -- --version
Piku remote operator.
Server: piku@roughdrafts.xyz
App: roughdrafts

v18.1.0
```

**Comment by chr15m** [comment]
Can you also paste the contents of you `Procfile` and `ENV` file?

**Comment by kinostl** [comment]
Procfile
```
web: npm run deploy 2>&1 | cat
```

ENV is entirely config:set

```
minty@mio:~/roughdrafts$ piku config
Piku remote operator.
Server: piku@roughdrafts.xyz
App: roughdrafts

DATABASE_URL=omitted
NGINX_HTTPS_ONLY=1
NGINX_SERVER_NAME=roughdrafts.xyz
AUTO_RESTART=1
DISCORD_KEY=omitted
DISCORD_SECRET=omitted
GRANT_ORIGIN=https://roughdrafts.xyz
RD_SECRET=omitted
NODE_VERSION=18.1.0
```

**Comment by chr15m** [comment]
I guess you have double checked everything in `dotenv/config` is present in the live environment. Hmmm.

Maybe try changing the Procfile to `/usr/bin/npm run deploy`?

**Comment by kinostl** [comment]
Yeah, I don't think it'd run manually if it wasn't. 

No difference with the explicit npm call.

I was thinking of just reinstalling the server and trying from fresh. I had a mess up with installing certbot and had to clean up after it, but I don't think that should effect this.

**Comment by chr15m** [comment]
Ok, sorry about that. Maybe try with a simpler Node/Express server to begin with. Just to check everything is working ok. You'll also need #240 (which hasn't been merged just yet by @rcarmo) for SSL to work properly.

**Comment by kinostl** [comment]
Yeah same thing with the simpler server. I'll go ahead and try reinstalling and report back if there isn't anything else to try testing.

```
minty@mio:/tmp/test_rd$ piku config:set NGINX_HTTPS_ONLY=1 NGINX_SERVER_NAME=roughdrafts.xyz AUTO_RESTART=1 
# lets encrypt stuff works as expected here
minty@mio:/tmp/test_rd$ cat *
var http = require('http');
 
http.createServer(function (req, res) {
	    res.writeHead(200, {'Content-Type': 'text/plain'});
	    res.end('Goodbye, World!\n');
}).listen(8080, '127.0.0.1');
{
  "name": "test_rd",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
web: node index.js 2>&1 | cat
minty@mio:/tmp/test_rd$ piku logs
Piku remote operator.
Server: piku@roughdrafts.xyz
App: roughdrafts

No logs found for app 'roughdrafts'.
```

**Comment by chr15m** [comment]
Ok, so this is probably a problem:

> `.listen(8080, '127.0.0.1');`

The server must listen on `$PORT` and `$BIND_ADDRESS` for Piku to connect nginx to it. You can use e.g. `process.env["PORT"] || 8080` to have `8080` as the port number in dev mode.

If there is a problem with the docs not explaining this clearly please let me know so I can fix it.

**Comment by kinostl** [comment]
Port was an oversight on my part. 

Bind address though - The server engine I'm using doesn't have bind address support. Is that explicitly required with piku? I was assuming it'd just find it out on its own somehow. 

```js
var http = require('http');
 
http.createServer(function (req, res) {
	    res.writeHead(200, {'Content-Type': 'text/plain'});
	    res.end('Goodbye, World!\n');
}).listen(process.env.PORT, process.env.BIND_ADDRESS);
```

Changed it to this and pushed, still the same 502 from what I assume is it not running the web worker correctly.

**Comment by chr15m** [comment]
I think most servers will bind to `127.0.0.1` by default which should hopefully work.

**Comment by kinostl** [comment]
Since this is happening with a simple server I'm gonna assume its something wrong with the way I installed piku. I'm reinstalling from new now.

**Comment by kinostl** [comment]
Fresh install, had to manually upgrade acme.sh after installing piku. Simple server worked. Testing with my node app now.

**Comment by kinostl** [comment]
App is loading the home screen now! Thanks :>

**Comment by kinostl** [comment]
You can probably safely close this as user error. Heres the events that lead to it.

1. Installed piku
2. Installed certbot
3. Don't touch server for 3 months
4. Ruined piku's nginx configs via Step 2
5. Attempted to fix Step 2 by removing everything except `include piku nginx configs` from the nginx configs
6. Attempted to make nodeenv work in an unintended way and mess with the piku.py file multiple times
7. Uninstall nodeenv and install nodejs and npm 18 instead of 16

Solution was to just reinstall from fresh and not use a dirty environment.

**Comment by chr15m** [comment]
lol, ok thanks very much for following up.
