### ISSUE TITLE
Monorepo support?

### ISSUE THREAD

**Issue by maxknerrich** [piku/piku#249]
Im quite new to piku but managed to deploy some simple nodejs Applications.
Now im trying to deploy a monorepo with an SvelteKit frontend and StrapiCMS backend.
Is that possible using piku?

**Comment by rcarmo** [comment]
Hi there,

It depends. I could not figure out what StrapiCMS actually does and how it works, but it boils down to a few ground rules:

- If you need a public URL, then that’s effectively one per app unless you handle routing on your own (for instance, mounting several paths in an Express app). You can always deploy two apps and point them to the same set of files/database/etc., though.
- If you can run things as separate processes (somehow), you can deploy any set of components in the same app (but you can only have one web worker proxied through `nginx`, unless you are really OK with using multiple ports, etc)

Given that both of the projects you named are JavaScript based, I suspect you can combine them with Express middleware somehow, although to be honest I just don’t do any kind of server-side JavaScript except Node-RED (which, incidentally, works fine under `piku`).

**Comment by chr15m** [comment]
@maxknerrich one thing I have found useful is to build static files into a subfolder and check them in, either in the main branch or in a bare repo (like gh-pages does). I think checking build artifacts into version control is underrated.
