### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/piku#25]
Ok, so there have been changes since I installed this on my raspberry pi.  Is it time to start tagging releases or is it still too early?

**Comment by rcarmo** [comment]
I've been avoiding that because I haven't gotten to the top of the README yet. I'd really like to have "1.0" support Node, or reliably deploy something else besides Python.

**Comment by dwightmulcahy** [comment]
v0.9?  Notice a bunch of *TODO* comments...  I might have time to take on the Java part since I noticed there isn't anything in it.

dWiGhT

**Comment by rcarmo** [comment]
I think we can start tagging releases now. :)

**Comment by dwightmulcahy** [comment]
Exciting!

**Comment by rcarmo** [comment]
OK, so this one needs doing. I'm going to see how to set up tags and releases and cut 1.0 ASAP
