### ISSUE TITLE
Issues with Node 16

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#252]
For some reason, Node 16 from NodeSource (at least) seems to not like the way we are trying to manage 'node_modules'. This has forced me to revert to Node 14 in one production machine (post-update) and requires further investigation.

**Comment by chr15m** [comment]
If you have some details about the error message or behavior you're seeing I can investigate.

**Comment by rcarmo** [comment]
I have finally set up an LXC environment to figure this out (and other things) and had to fix disabling IPv6 support first...

**Comment by rcarmo** [comment]
Bumping this so it doesn’t get stale. I’ve yet to do systematic tests, and in the meantime I’ll likely test with Node 18 or so now…

**Comment by rcarmo** [comment]
Unable to reproduce with Node 18. Closing for now.
