### ISSUE TITLE
SCALING file

### ISSUE THREAD

**Issue by dwightmulcahy** [piku/piku#26]
From reading `piku.py` the `SCALING` file is created by `piku.py` in the ENV_ROOT directory.  

I wonder if this would be useful to expose this into the APP_ROOT so that it could be created alongside the `ENV` file so that the process scaling could be created at the beginning instead of having to bump the processes with the `ps:scale` command.  I know this is a one time deal since the ENV_ROOT directory is persistent between deployments, just might be useful to have this as something that could be specified before deployment time.

**Comment by rcarmo** [comment]
Yes, that was part of my original intent, but I don’t recall why it isn’t that way by default. Let me toy with that notion a bit and see if I can recall exactly why (I suspect that since I could set `uwsgi` HTTP threads I neglected to fiddle with background workers...)

**Comment by delzac** [comment]
Sorry, has there been any resolution regarding this? What would the best practice of scaling number of app instance be? Using `ps:scale` or `UWSGI_PROCESSES` (doesn't this even make sense?) or something else?
