### ISSUE TITLE
Python 3.6 not supported for Ubuntu 22

### ISSUE THREAD

**Issue by ewalk153** [piku/piku#261]
CI is currently failing as we're using Ubuntu 22 and that host version does not have ruby 3.6 support. 

By bumping to the latest versions of actions/checkout and actions/setup-python, we [get the follow error message](https://github.com/piku/piku/actions/runs/3862379092/jobs/6583911043):
```
  Version 3.6 was not found in the local cache
  Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

The list of support versions (OS, arch, python) can be found here:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

I recommend we rollback to Ubuntu 20 or drop Python 3.6 from CI. Given the backward compat goals of this project, perhaps we stay with Ubuntu 20?

**Comment by rcarmo** [comment]
I'm tempted to drop Ubuntu 20, to be honest. I want to move to Python 3.8 and issue a deprecation warning if people are using 3.6 and 3.7, but I need to check what current Raspbian is shipping (on mobile, hence unable to check if it's already 3.9-ish like in Debian).

**Comment by ewalk153** [comment]
Ok, let's pin to Ubuntu 20.04 for now. 

This PR https://github.com/piku/piku/pull/260 makes the change (and bumps the tasks to the latest versions)

**Comment by ewalk153** [comment]
Looks like raspbian latest looks to be built on Debian bullseye. Bullseye ships with Python 3.9. 

https://packages.debian.org/bullseye/python3

**Comment by ewalk153** [comment]
#260 now give a green build.

**Comment by ewalk153** [comment]
^ Sorry if I misunderstood. I think you meant drop 3.6 and Ubuntu 20. Please confirm and I’ll tweak the PR. 

The rest of the ci fixes will stand.

**Comment by rcarmo** [comment]
Well, yes - but not now, and I'm happy to keep Ubuntu 20 around a little while more until we figure out if we should snapshot a Python 3.5 version and keep it as legacy, etc.

So thanks for this.
