### ISSUE TITLE
cgroup support

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#264]
It should be possible to use `cgroup-opt` on advanced deployments to limit the resource usage of `piku` apps so that a single app doesn't smother a small VPS/SBC.

**Comment by chr15m** [comment]
An alternative to this I've used before is to install rate-limiting middleware into your app and other techniques to diagnose and fix why the app is using more resources than you expect.

**Comment by rcarmo** [comment]
I’m really trying to cut down on CPU priority for batch processes and background workers so they don’t take CPU away from web workers. Unfortunately `uwsgi` seems to not use `cgroups` v2 at all and I can’t get that to work with either Ubuntu or Debian, so I’m looking into `cgclassify` as a workaround - and that may not be a good solution for `piku`…

**Comment by chr15m** [comment]
I would be happy to replace uwsgi with user-space systemd or some other process monitor if it came down to it. Pythonistas could bring their own wsgi or asgi server.

**Comment by rcarmo** [comment]
Yes, but `uwsgi` does so much for us now that we'd have to gut the entire project... I've since been doing some tests and independently confirmed unbit/uwsgi#2180 and unbit/uwsgi#2504, and that `cgrulesengd` seems to also be deprecated somewhat, so I'm closing this for now.

**Comment by chr15m** [comment]
Yeah there would be a lot of testing various edge cases and settings etc. to switch to something different.

**Comment by rcarmo** [comment]
In the meantime I've been tinkering [with the `cloud-init` installation](https://github.com/piku/cloud-init/tree/master/azure) and trying out a way to set up `cgroups` and process assignment rules. If it is manageable enough, I'll fold that back into the main project (but have already found a bug in the `systemd` path watcher, which was not monitoring `nginx` files correctly, at least in Ubuntu).
