### ISSUE TITLE
Simplified installation - removal of uwsgi-piku files

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#265]
Time has moved on a bit, and I realize that we no longer need the `uwsgi-piku` files, at least on Ubuntu:

For the past couple of years, the only thing I've had to do is to drop this into `/etc/uwsgi/apps-enabled/piku.ini`:

```ini
[uwsgi]
chdir = /home/piku/.piku/uwsgi
emperor = /home/piku/.piku/uwsgi-enabled
log-maxsize = 1048576
logto = /home/piku/.piku/uwsgi/uwsgi.log
log-backupname = /home/piku/.piku/uwsgi/uwsgi.old.log
socket = /home/piku/.piku/uwsgi/uwsgi.sock
uid = piku
gid = www-data
enable-threads = true
threads = 2
```

I'm going to see if this applies to Debian 11 as well (it really should), and if such, will remove those `systemd` files from the distribution (or move them to `legacy`) and update the docs accordingly.

(if anyone else can do it quicker, that is OK with me as well, right now I'm just reading and revising stuff and not messing about with test machines)

**Comment by rcarmo** [comment]
This is currently being tested [here](https://github.com/piku/cloud-init/tree/master/azure) and I hope to come to a definite conclusion soon. (once I have the `cloud-init` file set up for Ubuntu, I'll load it up on Proxmox and a Debian host).

**Comment by mariusa** [comment]
not stale

**Comment by rcarmo** [comment]
No, https://github.com/piku is the closest thing.

**Comment by avosa** [comment]
@rcarmo do you think we need one? #piku-website
