### ISSUE TITLE
Better Ruby support

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#267]
@ewalk153, since you've been spending some time on this, is there anything you think needs to be done to have better Ruby support? I was thinking along the lines of docs, a sample project, etc.

**Comment by ewalk153** [comment]
I’ll gladly take this on. I think examples and docs would be a good start.

**Comment by rcarmo** [comment]
Well, here you go: https://github.com/piku/sample-ruby-app (you have maintainer access).

**Comment by ewalk153** [comment]
I've pushed a Sinatra app. I'd like to add another more involved Ruby on Rails example (to mirror the Django app). Would you mind adding another repo for `sample-rails-app`?

To make keep security maintenance to a minimum, I'll keep the examples small and the dependency count low.

**Comment by rcarmo** [comment]
Done, you should have an invite for that as well.

**Comment by rcarmo** [comment]
Regarding maintenance and deps, I think you can just add a `dependabot.yml`. It's been working out great for me for Python and Node.
