### ISSUE TITLE
Elixir not found when installed with asdf

### ISSUE THREAD

**Issue by axelbdt** [piku/piku#270]
Hi,
I have installed Elixir on the distant server with asdf. I have installed it for the piku user so that it works from piku shell.
```bash
me@local:~$ piku shell
piku@server:~$ mix --version
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit:ns]
Mix 1.14.3 (compiled with Erlang/OTP 25)
```
However, the sample-phoenix-app won't deploy as the release script will crash with `mix: not found`.

Can you help me troubleshoot this so I can update the sample?
For instance, I am not sure if the git hook for push or deploy is called by the piku user.

Cheers

**Comment by chr15m** [comment]
When you run `piku shell` it will be importing additional env vars from `~/.profile` and `~/.bashrc` which are set via asdf.

What you need to do is figure out which of those env vars are being set, and then set them either in the `ENV` file or via `piku config:set`. If you do `piku shell` and then `export` you will see a list of ENV vars. You can hopefully work out from that exactly which ones need to be set.

**Comment by chr15m** [comment]
Another option would be to run the `asdf` setup inside your `release` script itself.

**Comment by axelbdt** [comment]
Reporting back: I have had no luck running it with asdf so far.
`. $HOME/.asdf/asdf.sh` in the release makes it complain with `Bad substitution`.

**Comment by chr15m** [comment]
What's your hash-bang on the release file? Try changing it to `/bin/bash`.
