### ISSUE TITLE
Ability to have multiple cron workers

### ISSUE THREAD

**Issue by chr15m** [piku/piku#272]
It would be good if people could install more than 1 cron running on different timers. A couple of times I have run into this and I ended up implementing a separate cron runner in the app instead.

At the moment the code seems to limit this:

https://github.com/piku/piku/blob/master/piku.py#L283

Not sure if uwsgi supports multiple cron workers.

**Comment by chr15m** [comment]
@rcarmo yes according to the [uwsgi docs on this](https://uwsgi-docs.readthedocs.io/en/latest/Cron.html#option-based-cron) you can just bang multiple cron entries in the ini:

> You can specify an unlimited number of option-based cron records.

```
[uwsgi]
cron = 59 2 -1 -1 -1 /usr/bin/backup_my_home --recursive
cron = 9 11 -1 -1 2 /opt/dem/bin/send_reminders
```

**Comment by abdulbasetbasher** [comment]
> I'm willing to bet just turning that nto a `^cron.+` regex would work. Need to try it, though.

you mean change CRON_REGEXP to  `^cron.+` ?
