### ISSUE TITLE
Remove uwsgi-piku.service / uwsgi-piku.dist , no longer needed to restart on config changes

### ISSUE THREAD

**Issue by mariusa** [piku/piku#279]
Hi,

Trying to install piku on Fedora/CentOS by going manually through
https://github.com/piku/piku-bootstrap/blob/main/playbooks/piku.yml

I've already installed `uwsgi` from  official repos:
```
dnf in -y uwsgi 
```
and it comes with `/usr/lib/systemd/system/uwsgi.service`
```
 systemctl start uwsgi
 systemctl status uwsgi
```
work fine.
Maybe these are also included in Ubuntu repos now?

If so, could this be removed?
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.service

There's also
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.dist
which goes into init.d, not sure why.

Built-in distro version also has
```
/etc/uwsgi.d
/etc/uwsgi.ini
```

Could the piku setup go in these 2 places instead of the 2 `piku/master/uwsgi` scripts?

**Comment by mariusa** [comment]
I see this https://github.com/piku/piku/blob/master/docs/ubuntu-18.04-bionic.md has the simplified version:
```
sudo ln /home/$PAAS_USERNAME/.piku/uwsgi/uwsgi.ini /etc/uwsgi/apps-enabled/piku.ini
sudo systemctl restart uwsgi
```

**Comment by rcarmo** [comment]
The simplified version is the way to go. Feel free to revise the merged docs and do another PR.

**Comment by rcarmo** [comment]
Yes, but linking alone increases the host attack service if I can get inside the piku user or one of its apps, so copying is the way to go here. Again, AFAICR the extra service was a way to avoid breaking the original one in earlier Ubuntu releases, not just to have it force-reload.On 23 Mar 2023, at 13:58, Marius A ***@***.***> wrote:﻿
Looks like this is enough for uwsgi setup:
ln -s /home/$PAAS_USERNAME/.piku/uwsgi/uwsgi.ini /etc/uwsgi.d/piku.ini

Per my understanding, these 2 files
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.service
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.dist
are just needed to reload uwsgi on config changes.
uwsgi does this already. Quoting from https://uwsgi-docs.readthedocs.io/en/latest/Emperor.html
Whenever an imperial monitor detects a new configuration file, a new uWSGI instance will be spawned with that configuration.
Whenever a configuration file is modified (its modification time changed, so touch --no-dereference may be your friend), the corresponding app will be reloaded.
Whenever a config file is removed, the corresponding app will be stopped.

**Comment by mariusa** [comment]
That makes sense.
I copied linking step from existing https://github.com/piku/piku/blob/master/docs/INSTALL-ubuntu-18.04-bionic.md
(and added `-s` to work on different filesystems)

Should that `ln` be replaced with `cp` in INSTALLs ?

> the extra service was a way to avoid breaking the original one in earlier Ubuntu releases

Are those still needed? It seems only this would do the job:
```
sudo cp /home/$PAAS_USERNAME/.piku/uwsgi/uwsgi.ini /etc/uwsgi/apps-enabled/piku.ini
```

**Comment by mariusa** [comment]
Back to the request:

Per my understanding, these 2 files
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.service
https://raw.githubusercontent.com/piku/piku/master/uwsgi-piku.dist
are just needed to reload uwsgi on config changes.

uwsgi does this already. Quoting from https://uwsgi-docs.readthedocs.io/en/latest/Emperor.html
```
Whenever an imperial monitor detects a new configuration file, a new uWSGI instance will be spawned with that configuration.
Whenever a configuration file is modified (its modification time changed, so touch --no-dereference may be your friend), the corresponding app will be reloaded.
Whenever a config file is removed, the corresponding app will be stopped.
```
I've tested this with `piku config:set A=b` and `piku logs' shows the app being restarted.

Would you please remove to 2 files, to avoid confusion with new setups?

**Comment by mariusa** [comment]
Dupe of https://github.com/piku/piku/issues/265
