### ISSUE TITLE
create ~/bin/piku symlink to ~/piku.py

### ISSUE THREAD

**Issue by mariusa** [piku/piku#290]
I'd like to run piku script after `su`-ing to piku user, instead of ssh.
It works if I do `~/piku.py`, but would like to be able to use just `piku`

What do you think about having the initial setup also do a
`ln -s ~/piku.py ~/bin/piku`
?

**Comment by rcarmo** [comment]
There's no real reason to SSH in and run `piku.py` by hand other than for testing (I certainly never do it, especially since the entire premise of the way it works is that you _don't_ need to log in to your servers. Also,  `piku` is sort of "taken" by @chr15m's local helper, so I'd prefer to avoid confusion.

**Comment by mariusa** [comment]
Ok, thanks. I've read somewhere that piku.py is set as the login shell and one could ssh to execute various options, but can't find that.

> the way it works is that you don't need to log in to your servers

Perfect. I thought it needed often logins, due to setting up ssh keys in INSTALL. I already have an user and just `su` to piku when needed.

**Comment by chr15m** [comment]
@mariusa if you use the `piku` helper script on your local you can SSH in to individual apps (ending up in their APP dir with environment configured for the) by doing `piku shell` in a git repo that has a piku remote configured.

**Comment by chr15m** [comment]
@mariusa FYI under the hood this simply executes the following:

```
ssh -t "$server" run "$app" bash
```

Where `$server` would be your remote and `$app` is the Piku app name.
