### ISSUE TITLE
New NGINX_HTTPS_ONLY logic breaks existing installs

### ISSUE THREAD

**Issue by chr15m** [piku/piku#291]
This line was changed to get rid of the`HTTPS_ONLY` var and only retain the `NGINX_HTTPS_ONLY` var:

https://github.com/piku/piku/blob/master/piku.py#L914

Unfortunately the truthiness logic was also changed. Now the setting can only be the literal string "true" whereas the previous check was simply for the var to be set at all: `'NGINX_HTTPS_ONLY' in env`. This breaks a considerable number of installs (including many of my own) which have e.g. `NGINX_HTTPS_ONLY=1` in their env or config.

I think we should use Python's builtin `ConfigParser.getboolean()` here which detects many variations of truthy/falsy-strings:

https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.getboolean

We could probably do this elsewhere in the code for booleanish env vars.

I'll put together a PR for this if nobody beats me to it.

**Comment by chr15m** [comment]
Found a Python internal that does this:

```
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "yes")
True
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "true")
True
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "on")
True
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "1")
True
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "ON")
True
>>> configparser.ConfigParser._convert_to_boolean(configparser.ConfigParser, "TRUE")
True
```

**Comment by rcarmo** [comment]
I’d rather not rely on internals - I’ve been burned before. How about a helper function that does that?

    value.lower() in [‘1’, ‘on’, ‘true’, ‘enabled’]

**Comment by chr15m** [comment]
Probably wise! Have force-pushed with an update that works like that.

**Comment by rcarmo** [comment]
LGTM
