### ISSUE TITLE
[feat] add config:push / config:pull for working with config vars

### ISSUE THREAD

**Issue by mariusa** [piku/piku#294]
This would allow setting all config vars at one from an `.env` key/value file, eg
```
heroku config:push -o -f .env.prd
```

as done by https://github.com/xavdid/heroku-config

**Comment by rcarmo** [comment]
This is what the ENV file is for. What is the advantage here?

**Comment by mariusa** [comment]
Can't use ENV file to keep secrets, as it's committed to git. Therefore, I'm using a separate `.env.prd` file with both secrets and non-secret vars. Basically, the goal is to have `piku set` read vars from a file, instead of only command line.

**Comment by chr15m** [comment]
Perhaps the solution is to document the technique mentioned in https://github.com/piku/piku/discussions/302

```
piku config:set `cat .env.prod`
```

This seems about as easy to remember and type as the Heroku oneliner you posted.

**Comment by mariusa** [comment]
If that would work properly, yes. Issues:

1. vars with spaces don't work (I'm using bash with Fedora 38). Tried with and without quotes:
```
 cat .env.test 
TEST1=t112


TEST2="t22 cd"

$ piku config:set `cat .env.test`
Piku remote operator.

Setting TEST2="t22 for 'app'
Error: malformed setting 'cd"'
```

2. (minor) Comments don't work -- lines starting with `#`

Seems it would be more reliable for piku to be able to read from a file, independent of what the current shell is set to.
