### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by matrixjnr** [piku/piku#30]
Can you implement a web interface for analytics?

**Comment by rcarmo** [comment]
Not in scope, sorry. I want to keep this small and simple.

**Comment by chr15m** [comment]
@matrixjnr this seems like something that could work well as a separate piku-deployable project repository. The sites deployed by piku all run as the user `piku` so you could build a simple site which wraps and calls `~/piku/piku.py` directly on the backend. People could then deploy it into their own piku instance by simply checking out and git push-ing it up.

**Comment by matrixjnr** [comment]
@chr15m I have been a bit busy but I'll definitely try creating a web UI for piku though I am more of a backend dev than frontend. Hope I get the job done.

**Comment by chr15m** [comment]
@rcarmo I needed some basic analytics for a project I am running under Piku and I was thinking about the simplest way to implement it. I realised I can run `goaccess` in "realtime" mode under a `web` worker. I can do this as a separate app so it doesn't have to go into piku, however `goaccess` wants an nginx/apache style combined log and these are currently commented out in the default nginx configs. Is there a reason not to have those access/error logs? Maybe an issue with logfiles filling up disk? Would you accept a patch for making this an ENV flag?

**Comment by rcarmo** [comment]
Hi!

I delegated all the log management to uWSGI, because I did not want to manage log files at all and Bottle/Flask/etc. already generate HTTP logs (which are usually richer in my case, since i add ms serving time and other fields and therefore make the nginx logs completely redundant). uWSGI also isolates things neatly in that regard.

In fact, I don’t think I look at HTTP logs anywhere directly these days (they’re usually sent off to some kind of centralized logging facility or there are better things like New Relic/X-Ray/App Insights), but I’m OK with making this a flag as long as rotation is set up and the logs are isolated between apps…

**Comment by chr15m** [comment]
After digging into this some more I've realized that the uwsgi process actually does the sensible thing and logs all stderr/stdout from the web application to that one place. It can't tell which logs (from the web app) are request logs and which are errors or other information. So I think uwsgi is the wrong place to do this and the best thing is to document what is happening by default with the logging and let the user do whatever they want (e.g. get their own app to log the requests). I also think it would be worth adding the flag to have nginx log the requests if the user wants but you are right that log rotation confuses this a bit. I'll have a think and cook up a documentation PR and maybe one for nginx logs again.

**Comment by chr15m** [comment]
So two possible solutions are:

 * Download the access logs with `piku run cat logs/access.log` or similar and then pipe them into e.g. `goaccess` running on your local.
 * Write a small analytics app and deploy it to your piku instance pointing at the right log file.

@rcarmo I think we can close this one.

**Comment by mmm8955405** [comment]
> So two possible solutions are:
> 
> * Download the access logs with `piku run cat logs/access.log` or similar and then pipe them into e.g. `goaccess` running on your local.
> * Write a small analytics app and deploy it to your piku instance pointing at the right log file.
> 
> @rcarmo I think we can close this one.

There is still no UI in 2023. This project should be dead

**Comment by chr15m** [comment]
@mmm8955405 The way open source works is if you want something you build it. Nobody owes you anything. Come back when you have a PR to contribute.

**Comment by mmm8955405** [comment]
> I do have a series of monitoring scripts that work as a standalone, bolt-on app, but if you think the project should be dead because it doesn't have a UI I'm afraid you're completely missing the point of why and how it exists.

It doesn't matter. Who wants to do some deployment with the command line. Who will pay attention to pikku when I wait for other big factories to finish

**Comment by mmm8955405** [comment]
> @mmm8955405 The way open source works is if you want something you build it. Nobody owes you anything. Come back when you have a PR to contribute.

You're right. You can also write an operating system, which has no problem at all. The only problem is that you don't let others comment on whether the wheels you make are suitable for vehicles
