### ISSUE TITLE
Suddenly getting Error: app 'myapp' not deployed!

### ISSUE THREAD

**Issue by mariusa** [piku/piku#300]
### Discussed in https://github.com/piku/piku/discussions/299

<div type='discussions-op-text'>

<sup>Originally posted by **mariusa** April  4, 2023</sup>
Hi,

After running few times `./piku.py restart myapp`, the app didn't start anymore. 

Last log is
```
web.1    | Tue Apr  4 12:41:34 2023 - received message 0 from emperor
web.1    | SIGINT/SIGTERM received...killing workers...
web.1    | [uwsgi-daemons] stopping daemon (pid: 33326): npm start 2>&1 | cat
web.1    | goodbye to uWSGI.
```

1. I don't why it didn't start afterwards

To solve this manually, I tried runing `./piku.py restart myapp`, but it gives
```
 Error: app 'myapp' not deployed!
```

The 2 `.ini` files exist in `uwsgi-available`, but folder `uwsgi-enabled` is empty. I couldn't figure out the difference between these 2 by looking on code.

```bash
$ piku ps
web:1
worker:1
```

2. What would be the cause & solution for this situation?

Thanks</div>

**Comment by mariusa** [comment]
To solve this -- copy-pasting code, don't know how to do another PR when an existing one is opened (and ignored)
```
def cmd_stop(app):
    """Stop an app, e.g: piku stop <app>"""
    app = exit_if_invalid(app)
    do_stop(app)

def do_stop(app):
    config = glob(join(UWSGI_ENABLED, '{}*.ini'.format(app)))

    if len(config) > 0:
        echo("Stopping app '{}'...".format(app), fg='yellow')
        for c in config:
            remove(c)
    else:
        echo("Error: app '{}' not deployed!".format(app), fg='red')

def do_restart(app):
    """Restarts a deployed app"""
    echo("restarting app '{}'...".format(app), fg='yellow') 
    do_stop(app)
    spawn_app(app)

```

`echo("Error: app '{}' not deployed!".format(app), fg='red')` is still wrong. App is deployed, just not running at the moment, need to start it.

**Comment by rcarmo** [comment]
That PR has no direct relevance onto the issue at hand as far as I can tell. Please be mindful of the limited time we have (and I would suggest catching up on git branching and how to do PRs from the CLI).

**Comment by mariusa** [comment]
> That PR has no direct relevance onto the issue at hand as far as I can tell.

Right. I don't know how to create another separate PR. As you said, I might learn that.

> Please be mindful of the limited time we have

Got it. I also invested quite some time in understanding part of the current code, improving it and coming up with the next patch.

**Comment by chaegribben** [comment]
I installed piku on a raspberry pi 3 today and everything was working fine until I restarted the pi, now I can't get anything to run anymore not matter whether I stop, deploy or restart in any order, even destroying the apps and pushing them again had no effect.
I get this message on attempts to restart despite the app being there
Error: app 'myapp' not deployed!

This appears to be related to the issue discussed here. Is there a known cause? I can't see in the PR what would actually fix this.

**Comment by mariusa** [comment]
Try it :) It should fix the issue.

Marius

**Comment by chaegribben** [comment]
Afraid not. replaced piku.py with the one from your PR and, although I don't get the not deployed message anymore, still nothing runs. None of the node commands I specify for the 'web' entry in my Procfile get run at all anymore. It's as if something didn't restart after I shutdown my pi and yet all of the piku commands are executing. I never get a log file for either of my apps anymore.

**Comment by mariusa** [comment]
Hope @chr15m or @rcarmo can share more insight

**Comment by rcarmo** [comment]
We’d need to know how it was installed, the OS version and (just a guess here) if the `uwsgi` service is enabled and running in `systemd` and picking up the changes piku does to the .ini files inside ~/.piku.

(there are minor differences in Linux distros regarding how `uwsgi` is configured to restart upon reboot and watch for changes)

It is those changes done by `piku.py`, when detected, that make `uwsgi` spawn the app processes. So if you could check if `uwsgi` is running and provide more details that would be helpful.
