### ISSUE TITLE
Is there a "build" stage

### ISSUE THREAD

**Issue by max-prtsr** [piku/piku#305]
E.g. I have a react app sources in my repo. I can't deploy them to `static` - I need to run `pnpm build` before I could serve them...

**Comment by rcarmo** [comment]
That is what the “release:” entry in the Procfile is for.

**Comment by max-prtsr** [comment]
@rcarmo there is no such record
https://github.com/piku/piku/blob/master/docs/DESIGN.md#procfile-format

**Comment by chr15m** [comment]
@max-prtsr you're right it should be in that document. It is documented here also: https://github.com/piku/piku#using-piku

You an also add a `post-install` script in the `scripts` section of your `package.json`.

Another option is to do your build on your local machine and commit it into either a branch (like one does for `gh-pages`) or a directory, and have the Profile serve the pre-compiled artifact.

**Comment by rcarmo** [comment]
Oh. I had just done that from my phone.
