### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#321]
Now that `bun` has reached 1.0, and given that it performs quite well on constricted environments like the Raspberry Pi, I am tempted to add support for it.

Current thoughts:

* We should assume `bun` is installed under the `piku` user
* Picking `bun` should be done if the binary exists in its standard install location _and_ `package.json` has it explicitly added to the `runtimes` section
* Otherwise, we would default to `nodejs`.

There are a few kinks to be sorted out since I haven't yet established if `bun` works OK with custom `node_module` paths, etc., but it should be feasible and something like a 10-line patch.

**Comment by chr15m** [comment]
Sounds great. Related to this I've been using pnpm instead of npm with node and I started putting together a patch to support it but got waylaid.

**Comment by rcarmo** [comment]
Minor update on this, since I'm online: [`bun` 1.0 doesn't implement `dgram`](https://github.com/oven-sh/bun/issues/1630), which I need for my ARM deployments, so this has dropped in priority a bit for me. I do have a test environment for it, so I might hack it in since it's a great mini-project for averting boredom.
