### ISSUE TITLE
MkDocs documentation

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#339]
I've decided to adopt [mkdocs-material](https://github.com/squidfunk/mkdocs-material) for a couple of other things, and I think it would be a good way to manage our docs. Will see if I can spare the cycles for it.

**Comment by rcarmo** [comment]
Just went ahead and did it. Will be moving all the docs to the `piku.github.io` repository ASAP, right now what's there is still WIP but serviceable.

**Comment by rcarmo** [comment]
And it's 95% done. Am just cleaning up this repo and making sure things point to sensible places.

**Comment by chr15m** [comment]
I noticed the front page links are broken. I guess you're still working on it but wanted to let you know in case.

**Comment by chr15m** [comment]
Oh never mind it's fixed!
