### ISSUE TITLE
go.mod support

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#340]
Needs to be done now that it's stabilised.

**Comment by psugand** [comment]
Any plans for implementing this?

**Comment by rcarmo** [comment]
Yes, but no schedule. We tend to implement (or accept PRs) when people are actively using this and can do troubleshooting, and right now I have more Rust projects than Go ones (and haven't yet tackled that), so... contributions are welcome. It really shouldn't be very hard, but I have very little bandwidth currently.

**Comment by psugand** [comment]
I don't mind giving it a go if you need a pair of extra hands. I will explore the code and let you know if I have any questions.

If you got any pointers or quick overview which would expedite things please share.

**Comment by rcarmo** [comment]
Sure, you can look at #344 for an example. The Go detection and deployment functions are just beside the ones I linked to in that, and the key thing is trying to make sure that GOPATH and equivalents are set to a place that is easy to clean up when the app is destroyed.

**Comment by psugand** [comment]
How would you propose the actual execution of applications to work?

I can see you have a `Procfile` defined, however, when deploying a Go app would you want the application to be compiled as a binary and then execute the binary ? or simply let the user specify the run path by pointing to their `main.go`, i.e. `go run cmd/main.go`

**Comment by rcarmo** [comment]
We don't need to be very prescriptive... For compiled languages, we typically use the `release` worker to run the build (if that fails, the app isn't (re)started). And then you can just invoke the resulting binary.

For simple stuff, `go run` is fine. One thing you can do is look at the sample repos (go back to the org tree, we try to have at least one sample per runtime) and build a tiny sample repo - I'd also welcome having that, since I hope to some day use those sample repos for end-to-end CI testing...

**Comment by rcarmo** [comment]
Here's an example: https://github.com/piku/sample-bare-metal-c/blob/master/Procfile

**Comment by chr15m** [comment]
That brings up an alternative way to deploy go apps that is already compatible with Piku. What you do is create a gh-pages type of branch called e.g. 'live' and you commit the compiled binary in there and use that to deploy to Piku. Alternatively you can commit the compiled binary into a sub-directory. Some people find the idea of committing binary artifacts a bit weird but I think there are actually advantages to this. If you go down this route check out the 'release' worker which you can use to do set up things etc.

**Comment by rcarmo** [comment]
I don't judge :)

**Comment by chr15m** [comment]
Fixed in #365 (I think?).
