### ISSUE TITLE
piku shell script broken under dash

### ISSUE THREAD

**Issue by chr15m** [piku/piku#358]
Whoops, looks like I didn't test #352 well enough. @clusterfudge just FYI on Ubuntu the shell script broke because the if statements are bash formatted where the hashbang is `/bin/sh`. Fix incoming.

**Comment by chr15m** [comment]
@clusterfudge I'll wait a day before merging this in case you want to test first as I don't know what shell you are using.

**Comment by clusterfudge** [comment]
Commented on the PR, thanks for fixing!
