### ISSUE TITLE
nginx auto-reload does not work on Ubuntu 20 (Focal)

### ISSUE THREAD

**Issue by sanand0** [piku/piku#377]
I followed the [Jammy installation instructions](https://piku.github.io/install/INSTALL-ubuntu-22.04-jammy.html) on my Focal system (Ubuntu 20.04.6 LTS). It worked fine *except for* nginx auto-reloading -- since [this commit](https://github.com/piku/piku/commit/00babe27798095b8b39914fc8d4ac953761cc1f5) changes the `systemctl` path.

```diff
-ExecStart=/bin/systemctl reload nginx
+ExecStart=/usr/bin/systemctl reload nginx
```

It took a while to debug this. Maybe we could:

**OPTION 1: Document this**. A mention on the [Installation on Ubuntu 22.04 LTS (Jammy)](https://piku.github.io/install/INSTALL-ubuntu-22.04-jammy.html) page saying:

> On Ubuntu 20 (Focal), modify `nginx.path` to replace `/usr/bin/systemctl` with `/bin/systemctl`

**OPTION 2: Handle it in ExecStart**. This change to `piku-nginx.service` might do the trick:

```diff
-ExecStart=/usr/bin/systemctl reload nginx
+ExecStart=/bin/bash -c '[ -x /usr/bin/systemctl ] && /usr/bin/systemctl reload nginx || /bin/systemctl reload nginx'
```

**Comment by chr15m** [comment]
This got auto-closed. Is it still an issue? I think your second proposed fix is great. Would you consider raising a PR? Thanks for reporting!
