### ISSUE TITLE
Question: how to upgrade piku?

### ISSUE THREAD

**Issue by dapicester** [piku/piku#385]
It seems there are no instructions to upgrade piku. I needed access to the `DATA_ROOT` variable from #360 but that was added only recently.

I checked the [ansible playboook](https://github.com/piku/piku-bootstrap/blob/main/playbooks/piku.yml) and it seems that ones only need this:
```py
 - name: Fetch piku.py script
      get_url:
        url: https://raw.githubusercontent.com/piku/piku/master/piku.py
        dest: ~/piku.py
        mode: 0700
```
At least, I did only that on my piku instance and it seems work well.

The questions: is the above correct? Is it possible to add to the documentation and/or to the ansible playbook?

**Comment by rcarmo** [comment]
Yes, that is correct. Adding it to the docs/playbook will eventually happen...
