### ISSUE TITLE
Support basic PHP-cgi installs

### ISSUE THREAD

**Issue by chr15m** [piku/piku#63]
Just going to put this out there. Don't worry, I don't expect anybody to work on this except me. ;)

https://github.com/wilmoore/php-version

**Comment by rcarmo** [comment]
Mind you, Debian distros seem to ship with a usable `uwsgi-plugin-php`. Might save you a lot of trouble :)

**Comment by chr15m** [comment]
https://www.codero.com/knowledge-base/content/3/392/en/how-to-serve-php-through-uwsgi-on-fedora-21-using-systemd-&-firewalld.html

**Comment by rcarmo** [comment]
Reopening since PHP is a thing I actually think we can support (see #222)
