### ISSUE TITLE
Support for Java

### ISSUE THREAD

**Issue by matrixjnr** [piku/piku#65]
I have tried adding support for Java but once I deploy a Java Application without an isolated environment an error File or Directory not found. Adding a virtualenv path piku automatically spins a python virtual environment and detects a Python App instead a Java App.
I know the directory must exist for the Live config and scaling files.
I did a dummy creation of the app's directory under .piku/envs(app) to enable Java deployments.

Check the demo below
[![asciicast](https://asciinema.org/a/257670.svg)](https://asciinema.org/a/257670)

I will create the PR soon, but make sure you have uswgi integration plugins. I am using jwsgi and jvm plugins.

**Comment by dwightmulcahy** [comment]
nice.  don't know of any venv for java but maybe you could use something like this: https://github.com/AlejandroRivera/maven-env

**Comment by dwightmulcahy** [comment]
or this which looks like a pyenv type for java:  http://www.jenv.be/

**Comment by matrixjnr** [comment]
I will try all of them and see which one works best. Though support for Spring Boot applications will need checking the availability of Spring Boot path and also updating the ```piku-bootstap``` file to start Spring Boot at Startup. I am not a Maven fun, but I will add Gradle builds too.

**Comment by matrixjnr** [comment]
Maven env builds with different maven versions, jenv isolates different java versions to be used. Which is better? Isolating the build tool(Which you can specify the language version) or isolating the language?

**Comment by dwightmulcahy** [comment]
hmmm if maven is the build tool I would just say have the latest version installed.  I will typically use the maven enforcer plugin to make sure I have a minimum version of maven installed.  

Isolating the java version might be the way to go given the 1.7/1.8/1.9 differences.

**Comment by rcarmo** [comment]
I’d keep it simple and use the versions shipping with the OS for a first pass - Java and Maven are not so much “stable” as “geologically timeless”, and then we’d keep the version choices as much off the code base as possible :)

**Comment by matrixjnr** [comment]
Since the maven wrapper allows users to use specific maven versions, I think jenv with maven wrapper would be perfect. Let me continue worrying on how uwsgi would run a complete java project instead of single java files.

**Comment by rcarmo** [comment]
I just merged #81, and think we’re well on our way to have a really nice solution (I particularly liked the sample being in Spark, which is a nice little framework). I’m going to keep this open until I can put together some setup instructions...

**Comment by chr15m** [comment]
This is cool, will test! One thing I'm particularly interested in is deploying Clojure uberjar's as web workers.

**Comment by chr15m** [comment]
Hey guys, I tested this out and I received the following error when pushing:

```
remote: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project spark-basic-structure: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.Processor (in unnamed module @0x53aa2fc9) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x53aa2fc9 -> [Help 1]
```

Is this because I'm running openjdk?

I suggest we also add a minimal Java example in the repo which just fires up a web worker, similar to the Python example.

**Comment by matrixjnr** [comment]
I will check it. Can you share your pom.xml file? Or the whole project?

**Comment by matrixjnr** [comment]
> Hey guys, I tested this out and I received the following error when pushing:
> 
> ```
> remote: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project spark-basic-structure: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.Processor (in unnamed module @0x53aa2fc9) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x53aa2fc9 -> [Help 1]
> ```
> 
> Is this because I'm running openjdk?
> 
> I suggest we also add a minimal Java example in the repo which just fires up a web worker, similar to the Python example.

I use Oracle's JDK for java development. I have no errors on my side. Regarding web workers for java it is a little bit not friendly since we are doing builds with maven or gradle. If you can know exact class file name you can spawn a worker from the `target/classes/*package name*/file.class` as:

`worker: java target/classes/packagename/test`

Otherwise creating web workers from jar files is pretty challenging.
Java files have to be compiled, I wish they could run like a python file.

**Comment by matrixjnr** [comment]
Support for Java is officially completed. If any error arise in future it can be opened.
