### ISSUE TITLE
RFC: GitHub org and repo splits

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#90]
This is more of a discussion thread - the former owner of @piku has agreed to forego his username so that we can build a GitHub org under that name, and I was thinking of splitting up this repository into two or three things in different repos:

* A (badly needed) documentation site (probably managed with something like docsifyj
* The core repo, with just the main Python script and required config files
* everything else (provisioning scripts, the Docker image I’ve been dabbling with, maybe even the scripts to build an SD card image I haven’t published)

Thoughts? I haven’t set up the org properly yet (just created it before breakfast to hold on to the name), but would like to get feedback before starting to break repo URLs and suchlike :)

**Comment by chr15m** [comment]
Interesting. What is the problem that split repositories will solve?

**Comment by chr15m** [comment]
BTW congratulations on the org that is very cool! :tada:

**Comment by rcarmo** [comment]
> Interesting. What is the problem that split repositories will solve?

Well, I'd like to have different repos for each deployment method (ansible, Azure, etc.) and one per sample app, for instance.

That way we can have things more readily deployable/re-usable, and each deployment method can just checkout the base PaaS repo without all the extraneous stuff that lives there now.

**Comment by chr15m** [comment]
Got it. Could I move [piku-redirect](https://github.com/chr15m/piku-redirect) and [piku-webdav](https://github.com/chr15m/piku-webdav) under the org as well?

**Comment by rcarmo** [comment]
Of course. They would make great sample apps.

**Comment by chr15m** [comment]
Also this: [piku-gitea](https://github.com/chr15m/piku-gitea). :sunglasses: (needs more testing but the basic deploy works).

**Comment by rcarmo** [comment]
Oh man. Gitea? Seriously? I love that!

I’m going to see if I can start moving things over the weekend.

**Comment by dwightmulcahy** [comment]
@chr15m ... I'm doing a fresh install of piku onto one of my rpis... I'll test out the piku-gitea and throw out some issues if I find anything.

**Comment by rcarmo** [comment]
I'm gonna close this one as the org is already set up and we're all happy (I think) :)
