### ISSUE TITLE
Pick static site generator for piku.github.io

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#92]
Following up on #90, I'm partial to picking out a simple static file generator to maintain all the docs:

* Standard Jekyll and `gh-pages` 
* `docsify` (which is cute and simple and lightweight but is lousy for SEO)
* Something else (suggestions?)

**Comment by rcarmo** [comment]
Jekyll theme option: https://github.com/mmistakes/minimal-mistakes [demo](https://mmistakes.github.io/minimal-mistakes/)

**Comment by chr15m** [comment]
millidocs looks very nice and clean.

**Comment by rcarmo** [comment]
Yeah, I’m leaning towards simple and clean too. Jekyll is a bit of a bother though (too much config).

**Comment by chr15m** [comment]
My only interaction with Jekyll has been the default `gh-pages` use. So I haven't run into any situation where I've needed to configure it at all. Operating in that mode it seems to handle documentation I've thrown at it pretty well. Maybe we could start with that default and then if we find we need something more complex transition later?

**Comment by rcarmo** [comment]
I’ve run a few moderately popular sites for local events on Jekyll, so I might be a bit jaded.

I was looking for something with good TOCs and navigation, but millidocs seems to be adequate for now, so I’ll look into it ASAP.

**Comment by chr15m** [comment]
@rcarmo I threw up a basic static site, hope that's ok!

https://piku.github.io/

Feel free to modify/replace it with whatever you want. Can I recommend my friend @retrogradeorbit's [bootleg](https://github.com/retrogradeorbit/bootleg) static site generator. It's small and simple and powerful just like Piku. :)

**Comment by chr15m** [comment]
I also noticed the domain piku.sh is free which could be a nice gateway.

**Comment by rcarmo** [comment]
Thanks. I am completely swamped these days and have had even less time than usual. And it’s not going to improve over the coming weeks...

**Comment by chr15m** [comment]
@rcarmo Understood. Well the great thing about Piku is it does not need much improvement with any great urgency because it was built right the first time. :)

**Comment by rcarmo** [comment]
I'm cool with bootleg (oh, how I miss Clojure). Trying to think how to get it to run inside gh-pages, will check if GitHub Actions have any way to deal with that.

**Comment by chr15m** [comment]
Or we could deploy to a Piku server instead. :)

**Comment by rcarmo** [comment]
I think we can close this one. We'll sort it out whenever new docs need to be written.
