### ISSUE TITLE
Linting and Tests

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#95]
So #94 drove home the point that we need automated linting and tests, and I'm thinking about doing that - either in CI or via some other GitHub app. 
Suggestions?

**Comment by chr15m** [comment]
I've used Travis & the built in Heroku CI. Travis would be fine for Piku I think.

**Comment by rcarmo** [comment]
Yeah, I use it for some things. I have applied for GItHub Actions and have access to AzureDevops, so it’s more about scoping out the testing required.

I have in mind three things:

- Linting
- Basic standalone tests
- Full-on deployment against a Docker container (have pushed a new repo to build that test image)

All of these can be done in Travis, I would just like to have (for instance) sane integration of the linter with GitHub PRs.

**Comment by jsenin** [comment]
I usually have two git hooks. First pre-commit hook, who checks if some .py file has changed and pass it through linter and formater (pylint and yapf), and then it runs unit tests. And sencondly pre-push hook who pass linter over all code and runs all tests (unit test, integration, functional etc..). Also there is a pipeline or tasks at jenkins running all kind of tests in order to detect a non 'pre-checked' push.

**Comment by dwightmulcahy** [comment]
hooks on the server-side would be a better solution since client-side would require everyone to install those hooks.

**Comment by rcarmo** [comment]
I just added this Action to the main repo: 

https://github.com/cclauss/GitHub-Action-for-pylint

I'm still figuring out the differences between GitHub Actions and Azure DevOps test stages, but it's a start.

**Comment by dwightmulcahy** [comment]
is it possible to do pylint in Travis?  It might be a good start to building up to getting some tests in this.

**Comment by rcarmo** [comment]
This is exactly the same as Travis from a functional perspective (the YAML is even similar) - but I'm not getting it to work on pull requests yet, I need to figure out why.

**Comment by dwightmulcahy** [comment]
we are mostly maven/jenkins/makefiles at work but I've started to poke around using Github Actions but haven't moved to it yet.

**Comment by rcarmo** [comment]
It feels and smells largely the same as Travis and Azure Pipelines - check out the .github folder on the top level of the repo, I think I've figured it out by now (but the next PRs will be the true test)

**Comment by rcarmo** [comment]
Also note that I'm just using pyflake8 temporarily - it's better than nothing for now, but eventually I'll look at `black` again.

**Comment by rcarmo** [comment]
OK, it seems to work OK for pushes (and caught a few things I've fixed). Let's see how it goes for a few days (with regard to PRs, especially - if you guys could re-push some of yours and see what happens...)

**Comment by jsenin** [comment]
Ok

El 20 de noviembre de 2019 20:44:09 CET, Rui Carmo <notifications@github.com> escribió:
>OK, it seems to work OK for pushes (and caught a few things I've
>fixed). Let's see how it goes for a few days (with regard to PRs,
>especially - if you guys could re-push some of yours and see what
>happens...)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/piku/piku/issues/95#issuecomment-556300994

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by rcarmo** [comment]
Ok. Now that we have basic linting (which complained about a bunch of variables not actual in use, even with my lazy use of locals() for some formatting), we need a test suite.

My original plan was to build a container with everything installed, mount piku.py inside it, and actually grab a sample and push it into the container via SSH. However, there is certainly lower-hanging fruit to tackle first, like unit testing each critical function.

Thoughts?

**Comment by jsenin** [comment]
use doubles for mocking( spy/ stub ) or monkey patching ^^

El 21 de noviembre de 2019 9:20:03 CET, Rui Carmo <notifications@github.com> escribió:
>Ok. Now that we have basic linting (which complained about a bunch of
>variables not actual in use, even with my lazy use of locals() for some
>formatting), we need a test suite.
>
>My original plan was to build a container with everything installed,
>mount piku.py inside it, and actually grab a sample and push it into
>the container via SSH. However, there is certainly lower-hanging fruit
>to tackle first, like unit testing each critical function.
>
>Thoughts?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/piku/piku/issues/95#issuecomment-556972150

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by chr15m** [comment]
Statistically speaking, formal code review has the highest probability of catching bugs, but tests are also good. @rcarmo I had half a rig built using Vagrant to spin up a machine and run the piku deploy scripts. Maybe I should finish it off?

**Comment by rcarmo** [comment]
@chr15m yes, of course. But we can probably  re-use that inside Docker, which we can run inside GitHub actions - once I finish https://github.com/piku/docker-debian... Maybe you can take a look at that.

**Comment by chr15m** [comment]
The linting is great so far! :+1:

**Comment by rcarmo** [comment]
Yeah, although I find flake8 to be a bit pedantic with whitespace.

**Comment by rcarmo** [comment]
FYI, due to my bungling the fix with #150 (since it was, in fact, a security issue to run stuff as `root`) and causing #154, commit 2c53bf97a22cfaf3e2d68aeb927a0539a1fbec79 now tries to run `piku` before linting.

**Comment by rcarmo** [comment]
In order to avoid a repeat of #156, I'm going to be adding a new test to run Piku solely with the current OS packages for Debian Buster and Ubuntu 18.04 (those will be done with Docker and will later be useful for doing actual deployment tests...)

**Comment by rcarmo** [comment]
And that's done via cc09a57fad37b515ed4886400325cdb0256eebf5.

Right now the `Dockerfiles` are identical for both Debian Buster and Ubuntu Bionic, and I could generalize things with Docker args, but I learned the hard way to do completely separate `Dockerfiles` per distro due to minor variations.

If anyone thinks that is useful, I can also do an Alpine variant and make sure we can run `piku` on the latest version solely with OS packages (or a minimum thereof).

And, of course, we can now extend this to do full-blown tests with whatever we feel like...

**Comment by chr15m** [comment]
Amazing! Alpine variant would be cool.

WRT bootstrapping things lately I've been looking for pure bash solutions to Ansible style idempotent provisioning and [bash booster](http://www.bashbooster.net/) looks interesting though it lacks quite a few basic operations the current Piku bootstrap requires.

**Comment by rcarmo** [comment]
I’m testing `cloud-config` in the meantime (I use it for most everything else on the cloud), will split it off to a repo soon. 

Alpine will be there in a little while, I just need to rip off my Node-RED Dockerfiles...
